using CloneBookingAPI.Database.Models.Review;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Database.Configurations.Review
{
    public class SuggestionReviewGradesConfiguration : IEntityTypeConfiguration<SuggestionReviewGrade>
    {
        public void Configure(EntityTypeBuilder<SuggestionReviewGrade> builder)
        {
            builder.HasData(
              new SuggestionReviewGrade[]
              {
                  new SuggestionReviewGrade { Id = 1, Value = 10, ReviewCategoryId = 1, ReviewId = 1, },
                  new SuggestionReviewGrade { Id = 2, Value = 9, ReviewCategoryId = 2, ReviewId = 2, },
                  new SuggestionReviewGrade { Id = 3, Value = 10, ReviewCategoryId = 3, ReviewId = 3, },
                  new SuggestionReviewGrade { Id = 4, Value = 9, ReviewCategoryId = 4, ReviewId = 4, },
                  new SuggestionReviewGrade { Id = 5, Value = 10, ReviewCategoryId = 5, ReviewId = 5, },
                  new SuggestionReviewGrade { Id = 6, Value = 10, ReviewCategoryId = 6, ReviewId = 6, },
                  new SuggestionReviewGrade { Id = 7, Value = 10, ReviewCategoryId = 7, ReviewId = 7, },
                  new SuggestionReviewGrade { Id = 8, Value = 9, ReviewCategoryId = 8, ReviewId = 8, },
                  new SuggestionReviewGrade { Id = 9, Value = 9, ReviewCategoryId = 9, ReviewId = 9, },
                  new SuggestionReviewGrade { Id = 10, Value = 9, ReviewCategoryId = 10, ReviewId = 10, },
                  new SuggestionReviewGrade { Id = 11, Value = 10, ReviewCategoryId = 11, ReviewId = 11, },
                  new SuggestionReviewGrade { Id = 12, Value = 9, ReviewCategoryId = 12, ReviewId = 12, },
                  new SuggestionReviewGrade { Id = 13, Value = 9, ReviewCategoryId = 1, ReviewId = 13, },
                  new SuggestionReviewGrade { Id = 14, Value = 9, ReviewCategoryId = 2, ReviewId = 14, },
                  new SuggestionReviewGrade { Id = 15, Value = 9, ReviewCategoryId = 3, ReviewId = 15, },
                  new SuggestionReviewGrade { Id = 16, Value = 10, ReviewCategoryId = 4, ReviewId = 16, },
                  new SuggestionReviewGrade { Id = 17, Value = 10, ReviewCategoryId = 5, ReviewId = 17, },
                  new SuggestionReviewGrade { Id = 18, Value = 9, ReviewCategoryId = 6, ReviewId = 18, },
                  new SuggestionReviewGrade { Id = 19, Value = 9, ReviewCategoryId = 7, ReviewId = 19, },
                  new SuggestionReviewGrade { Id = 20, Value = 9, ReviewCategoryId = 8, ReviewId = 20, },
                  new SuggestionReviewGrade { Id = 21, Value = 9, ReviewCategoryId = 9, ReviewId = 21, },
                  new SuggestionReviewGrade { Id = 22, Value = 9, ReviewCategoryId = 10, ReviewId = 22, },
                  new SuggestionReviewGrade { Id = 23, Value = 9, ReviewCategoryId = 11, ReviewId = 23, },
                  new SuggestionReviewGrade { Id = 24, Value = 10, ReviewCategoryId = 12, ReviewId = 24, },
                  new SuggestionReviewGrade { Id = 25, Value = 9, ReviewCategoryId = 1, ReviewId = 25, },
                  new SuggestionReviewGrade { Id = 26, Value = 10, ReviewCategoryId = 2, ReviewId = 26, },
                  new SuggestionReviewGrade { Id = 27, Value = 6, ReviewCategoryId = 3, ReviewId = 27, },
                  new SuggestionReviewGrade { Id = 28, Value = 9, ReviewCategoryId = 4, ReviewId = 28, },
                  new SuggestionReviewGrade { Id = 29, Value = 6, ReviewCategoryId = 5, ReviewId = 29, },
                  new SuggestionReviewGrade { Id = 30, Value = 4, ReviewCategoryId = 6, ReviewId = 30, },
                  new SuggestionReviewGrade { Id = 31, Value = 9, ReviewCategoryId = 7, ReviewId = 31, },
                  new SuggestionReviewGrade { Id = 32, Value = 3, ReviewCategoryId = 8, ReviewId = 32, },
                  new SuggestionReviewGrade { Id = 33, Value = 8, ReviewCategoryId = 9, ReviewId = 33, },
                  new SuggestionReviewGrade { Id = 34, Value = 5, ReviewCategoryId = 10, ReviewId = 34, },
                  new SuggestionReviewGrade { Id = 35, Value = 7, ReviewCategoryId = 11, ReviewId = 35, },
                  new SuggestionReviewGrade { Id = 36, Value = 9, ReviewCategoryId = 12, ReviewId = 36, },
                  new SuggestionReviewGrade { Id = 37, Value = 9, ReviewCategoryId = 6, ReviewId = 37, },
                  new SuggestionReviewGrade { Id = 38, Value = 9, ReviewCategoryId = 7, ReviewId = 38, },
                  new SuggestionReviewGrade { Id = 39, Value = 9, ReviewCategoryId = 8, ReviewId = 39, },
                  new SuggestionReviewGrade { Id = 40, Value = 9, ReviewCategoryId = 9, ReviewId = 40, },
                  new SuggestionReviewGrade { Id = 41, Value = 9, ReviewCategoryId = 10, ReviewId = 41, },
                  new SuggestionReviewGrade { Id = 42, Value = 9, ReviewCategoryId = 11, ReviewId = 42, },
                  new SuggestionReviewGrade { Id = 43, Value = 10, ReviewCategoryId = 12, ReviewId = 43, },
                  new SuggestionReviewGrade { Id = 44, Value = 10, ReviewCategoryId = 6, ReviewId = 44, },
                  new SuggestionReviewGrade { Id = 45, Value = 9, ReviewCategoryId = 7, ReviewId = 45, },
                  new SuggestionReviewGrade { Id = 46, Value = 9, ReviewCategoryId = 8, ReviewId = 46, },
                  new SuggestionReviewGrade { Id = 47, Value = 10, ReviewCategoryId = 9, ReviewId = 47, },
                  new SuggestionReviewGrade { Id = 48, Value = 9, ReviewCategoryId = 10, ReviewId = 48, },
                  new SuggestionReviewGrade { Id = 49, Value = 10, ReviewCategoryId = 11, ReviewId = 49, },
                  new SuggestionReviewGrade { Id = 50, Value = 10, ReviewCategoryId = 12, ReviewId = 50, },
                  new SuggestionReviewGrade { Id = 51, Value = 10, ReviewCategoryId = 6, ReviewId = 51, },
                  new SuggestionReviewGrade { Id = 52, Value = 9, ReviewCategoryId = 7, ReviewId = 52, },
                  new SuggestionReviewGrade { Id = 53, Value = 9, ReviewCategoryId = 8, ReviewId = 53, },
                  new SuggestionReviewGrade { Id = 54, Value = 10, ReviewCategoryId = 9, ReviewId = 54, },
                  new SuggestionReviewGrade { Id = 55, Value = 10, ReviewCategoryId = 10, ReviewId = 55, },
                  new SuggestionReviewGrade { Id = 56, Value = 10, ReviewCategoryId = 11, ReviewId = 56, },
                  new SuggestionReviewGrade { Id = 57, Value = 10, ReviewCategoryId = 12, ReviewId = 57, },
                  new SuggestionReviewGrade { Id = 58, Value = 10, ReviewCategoryId = 6, ReviewId = 58, },
                  new SuggestionReviewGrade { Id = 59, Value = 9, ReviewCategoryId = 7, ReviewId = 59, },
                  new SuggestionReviewGrade { Id = 60, Value = 9, ReviewCategoryId = 8, ReviewId = 60, },
                  new SuggestionReviewGrade { Id = 61, Value = 10, ReviewCategoryId = 9, ReviewId = 61, },
                  new SuggestionReviewGrade { Id = 62, Value = 9, ReviewCategoryId = 10, ReviewId = 62, },
                  new SuggestionReviewGrade { Id = 63, Value = 10, ReviewCategoryId = 11, ReviewId = 63, },
                  new SuggestionReviewGrade { Id = 64, Value = 10, ReviewCategoryId = 12, ReviewId = 64, },
                  new SuggestionReviewGrade { Id = 65, Value = 10, ReviewCategoryId = 6, ReviewId = 65, },
                  new SuggestionReviewGrade { Id = 66, Value = 9, ReviewCategoryId = 7, ReviewId = 66, },
                  new SuggestionReviewGrade { Id = 67, Value = 9, ReviewCategoryId = 8, ReviewId = 67, },
                  new SuggestionReviewGrade { Id = 68, Value = 10, ReviewCategoryId = 9, ReviewId = 68, },
                  new SuggestionReviewGrade { Id = 69, Value = 9, ReviewCategoryId = 10, ReviewId = 69, },
                  new SuggestionReviewGrade { Id = 70, Value = 10, ReviewCategoryId = 11, ReviewId = 70, },
                  new SuggestionReviewGrade { Id = 71, Value = 10, ReviewCategoryId = 12, ReviewId = 71, },
                  new SuggestionReviewGrade { Id = 72, Value = 10, ReviewCategoryId = 6, ReviewId = 72, },
                  new SuggestionReviewGrade { Id = 73, Value = 9, ReviewCategoryId = 7, ReviewId = 73, },
                  new SuggestionReviewGrade { Id = 74, Value = 9, ReviewCategoryId = 8, ReviewId = 74, },
                  new SuggestionReviewGrade { Id = 75, Value = 10, ReviewCategoryId = 9, ReviewId = 75, },
                  new SuggestionReviewGrade { Id = 76, Value = 9, ReviewCategoryId = 10, ReviewId = 76, },
                  new SuggestionReviewGrade { Id = 77, Value = 9, ReviewCategoryId = 11, ReviewId = 77, },
                  new SuggestionReviewGrade { Id = 78, Value = 9, ReviewCategoryId = 12, ReviewId = 78, },
                  new SuggestionReviewGrade { Id = 79, Value = 10, ReviewCategoryId = 6, ReviewId = 79, },
                  new SuggestionReviewGrade { Id = 80, Value = 9, ReviewCategoryId = 7, ReviewId = 80, },
                  new SuggestionReviewGrade { Id = 81, Value = 9, ReviewCategoryId = 8, ReviewId = 81, },
                  new SuggestionReviewGrade { Id = 82, Value = 9, ReviewCategoryId = 9, ReviewId = 82, },
                  new SuggestionReviewGrade { Id = 83, Value = 9, ReviewCategoryId = 10, ReviewId = 83, },
                  new SuggestionReviewGrade { Id = 84, Value = 9, ReviewCategoryId = 11, ReviewId = 84, },
                  new SuggestionReviewGrade { Id = 85, Value = 10, ReviewCategoryId = 12, ReviewId = 85, },
              });
        }
    }
}
