using CloneBookingAPI.Database.Models.Suggestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Database.Configurations.Suggestions
{
    public class ApartmentsConfiguration : IEntityTypeConfiguration<Apartment>
    {
        public void Configure(EntityTypeBuilder<Apartment> builder)
        {
            builder.HasData(
              new Apartment[]
              {
                  new Apartment { Id = 1, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 52, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 2, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 65, BathroomsAmount = 1,
                                  ApartmentSize = 53, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 3, SuggestionId = 27, Description = "Test apartment description 3", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 50, BathroomsAmount = 1,
                                  ApartmentSize = 55, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 4, SuggestionId = 57, Description = "Test apartment description 4", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 60, BathroomsAmount = 1,
                                  ApartmentSize = 49, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 5, SuggestionId = 101, Description = "Test apartment description 5", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 55, BathroomsAmount = 1,
                                  ApartmentSize = 45, IsSmokingAllowed = false, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 6, SuggestionId = 1, Description = "Test apartment description 6", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 55, BathroomsAmount = 1,
                                  ApartmentSize = 55, IsSmokingAllowed = false, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 7, SuggestionId = 15, Description = "Test apartment description 7", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 65, BathroomsAmount = 1,
                                  ApartmentSize = 50, IsSmokingAllowed = true, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 8, SuggestionId = 27, Description = "Test apartment description 8", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 60, IsSmokingAllowed = false, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 9, SuggestionId = 57, Description = "Test apartment description 9", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 70, IsSmokingAllowed = false, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 10, SuggestionId = 101, Description = "Test apartment description 10", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 155, BathroomsAmount = 1,
                                  ApartmentSize = 75, IsSmokingAllowed = true, IsSuite = true, Name = "Single Suite Apartment",
                                  },
                  new Apartment { Id = 11, SuggestionId = 1, Description = "Test apartment description 11", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 70, IsSmokingAllowed = false, IsSuite = false, Name = "Double Apartment",
                                  },
                  new Apartment { Id = 12, SuggestionId = 15, Description = "Test apartment description 12", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 135, BathroomsAmount = 1,
                                  ApartmentSize = 75, IsSmokingAllowed = true, IsSuite = false, Name = "Double Apartment",
                                  },
                  new Apartment { Id = 13, SuggestionId = 27, Description = "Test apartment description 13", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 80, IsSmokingAllowed = true, IsSuite = false, Name = "Double Apartment",
                                  },
                  new Apartment { Id = 14, SuggestionId = 28, Description = "Test apartment description 14", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 118, BathroomsAmount = 1,
                                  ApartmentSize = 85, IsSmokingAllowed = false, IsSuite = false, Name = "Double Apartment",
                                  },
                  new Apartment { Id = 15, SuggestionId = 101, Description = "Test apartment description 15", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 95, BathroomsAmount = 1,
                                  ApartmentSize = 81, IsSmokingAllowed = false, IsSuite = false, Name = "Double Apartment",
                                  },
                  new Apartment { Id = 16, SuggestionId = 1, Description = "Test apartment description 16", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 100, BathroomsAmount = 1,
                                  ApartmentSize = 67, IsSmokingAllowed = false, IsSuite = true, Name = "Double Suite Apartment",
                                  },
                  new Apartment { Id = 17, SuggestionId = 15, Description = "Test apartment description 17", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 120, BathroomsAmount = 1,
                                  ApartmentSize = 94, IsSmokingAllowed = true, IsSuite = true, Name = "Double Suite Apartment",
                                  },
                  new Apartment { Id = 18, SuggestionId = 27, Description = "Test apartment description 18", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 200, BathroomsAmount = 1,
                                  ApartmentSize = 100, IsSmokingAllowed = false, IsSuite = true, Name = "Double Suite Apartment",
                                  },
                  new Apartment { Id = 19, SuggestionId = 57, Description = "Test apartment description 19", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 250, BathroomsAmount = 1,
                                  ApartmentSize = 89, IsSmokingAllowed = true, IsSuite = true, Name = "Double Suite Apartment",
                                  },
                  new Apartment { Id = 20, SuggestionId = 101, Description = "Test apartment description 20", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 250, BathroomsAmount = 1,
                                  ApartmentSize = 101, IsSmokingAllowed = false, IsSuite = true, Name = "Double Suite Apartment",
                                  },
                  new Apartment { Id = 21, SuggestionId = 1, Description = "Test apartment description 21", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 100, IsSmokingAllowed = false, IsSuite = false, Name = "Triple Apartment",
                                  },
                  new Apartment { Id = 22, SuggestionId = 19, Description = "Test apartment description 22", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 150, BathroomsAmount = 1,
                                  ApartmentSize = 98, IsSmokingAllowed = true, IsSuite = false, Name = "Triple Apartment",
                                  },
                  new Apartment { Id = 23, SuggestionId = 27, Description = "Test apartment description 23", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 125, BathroomsAmount = 2,
                                  ApartmentSize = 105, IsSmokingAllowed = true, IsSuite = false, Name = "Triple Apartment",
                                  },
                  new Apartment { Id = 24, SuggestionId = 57, Description = "Test apartment description 24", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 225, BathroomsAmount = 2,
                                  ApartmentSize = 115, IsSmokingAllowed = true, IsSuite = false, Name = "Triple Apartment",
                                 },
                  new Apartment { Id = 25, SuggestionId = 101, Description = "Test apartment description 25", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 320, BathroomsAmount = 2,
                                  ApartmentSize = 112, IsSmokingAllowed = false, IsSuite = false, Name = "Triple Apartment",
                                  },
                  new Apartment { Id = 26, SuggestionId = 1, Description = "Test apartment description 26", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 250, BathroomsAmount = 2,
                                  ApartmentSize = 109, IsSmokingAllowed = false, IsSuite = true, Name = "Triple Suite Apartment",
                                  },
                  new Apartment { Id = 27, SuggestionId = 15, Description = "Test apartment description 27", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 650, BathroomsAmount = 1,
                                  ApartmentSize = 107, IsSmokingAllowed = false, IsSuite = true, Name = "Triple Suite Apartment",
                                  },
                  new Apartment { Id = 28, SuggestionId = 27, Description = "Test apartment description 28", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 125, BathroomsAmount = 2,
                                  ApartmentSize = 121, IsSmokingAllowed = false, IsSuite = true, Name = "Triple Suite Apartment",
                                  },
                  new Apartment { Id = 29, SuggestionId = 57, Description = "Test apartment description 29", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 225, BathroomsAmount = 1,
                                 ApartmentSize = 98, IsSmokingAllowed = true, IsSuite = true, Name = "Triple Suite Apartment",
                                  },
                  new Apartment { Id = 30, SuggestionId = 101, Description = "Test apartment description 30", RoomsAmount = 3,
                                  GuestsLimit = 3, PriceInUSD = 355, BathroomsAmount = 2,
                                 ApartmentSize = 95, IsSmokingAllowed = true, IsSuite = true, Name = "Triple Suite Apartment",
                                  },
                  new Apartment { Id = 31, SuggestionId = 1, Description = "Test apartment description 31", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 250, BathroomsAmount = 2,
                                  ApartmentSize = 103, IsSmokingAllowed = true, IsSuite = false, Name = "Quadruple Apartment",
                                  },
                  new Apartment { Id = 32, SuggestionId = 23, Description = "Test apartment description 32", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 750, BathroomsAmount = 2,
                                  ApartmentSize = 120, IsSmokingAllowed = false, IsSuite = false, Name = "Quadruple Apartment",
                                  },
                  new Apartment { Id = 33, SuggestionId = 27, Description = "Test apartment description 33", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 124, IsSmokingAllowed = false, IsSuite = false, Name = "Quadruple Apartment",
                                  },
                  new Apartment { Id = 34, SuggestionId = 57, Description = "Test apartment description 34", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 225, BathroomsAmount = 1,
                                  ApartmentSize = 130, IsSmokingAllowed = false, IsSuite = false, Name = "Quadruple Apartment",
                                  },
                  new Apartment { Id = 35, SuggestionId = 101, Description = "Test apartment description 35", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 355, BathroomsAmount = 2,
                                  ApartmentSize = 135, IsSmokingAllowed = false, IsSuite = false, Name = "Quadruple Apartment",
                                  },
                  new Apartment { Id = 36, SuggestionId = 1, Description = "Test apartment description 36", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 325, BathroomsAmount = 2,
                                  ApartmentSize = 130, IsSmokingAllowed = true, IsSuite = true, Name = "Quadruple Suite Apartment",
                                  },
                  new Apartment { Id = 37, SuggestionId = 15, Description = "Test apartment description 37", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 365, BathroomsAmount = 2,
                                  ApartmentSize = 140, IsSmokingAllowed = true, IsSuite = true, Name = "Quadruple Suite Apartment",
                                  },
                  new Apartment { Id = 38, SuggestionId = 27, Description = "Test apartment description 38", RoomsAmount = 4,
                                  GuestsLimit = 4, PriceInUSD = 225, BathroomsAmount = 2,
                                  ApartmentSize = 132, IsSmokingAllowed = false, IsSuite = true, Name = "Quadruple Suite Apartment",
                                  },
                  new Apartment { Id = 39, SuggestionId = 57, Description = "Test apartment description 39", RoomsAmount = 4,
                                  GuestsLimit = 4, PriceInUSD = 325, BathroomsAmount = 2,
                                  ApartmentSize = 129, IsSmokingAllowed = false, IsSuite = true, Name = "Quadruple Suite Apartment",
                                  },
                  new Apartment { Id = 40, SuggestionId = 101, Description = "Test apartment description 40", RoomsAmount = 4,
                                  GuestsLimit = 4, PriceInUSD = 355, BathroomsAmount = 1,
                                  ApartmentSize = 129, IsSmokingAllowed = true, IsSuite = true, Name = "Quadruple Suite Apartment",
                                  },
                  new Apartment { Id = 41, SuggestionId = 1, Description = "Test apartment description 41", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 225, BathroomsAmount = 2,
                                  ApartmentSize = 130, IsSmokingAllowed = false, IsSuite = false, Name = "Quintuple Apartment",
                                  },
                  new Apartment { Id = 42, SuggestionId = 15, Description = "Test apartment description 42", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 600, BathroomsAmount = 2,
                                  ApartmentSize = 132, IsSmokingAllowed = false, IsSuite = false, Name = "Quintuple Apartment",
                                  },
                  new Apartment { Id = 43, SuggestionId = 27, Description = "Test apartment description 43", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 425, BathroomsAmount = 2,
                                  ApartmentSize = 133, IsSmokingAllowed = true, IsSuite = false, Name = "Quintuple Apartment",
                                  },
                  new Apartment { Id = 44, SuggestionId = 57, Description = "Test apartment description 44", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 425, BathroomsAmount = 2,
                                  ApartmentSize = 140, IsSmokingAllowed = true, IsSuite = false, Name = "Quintuple Apartment",
                                  },
                  new Apartment { Id = 45, SuggestionId = 101, Description = "Test apartment description 45", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 355, BathroomsAmount = 2,
                                  ApartmentSize = 98, IsSmokingAllowed = true, IsSuite = false, Name = "Quintuple Apartment",
                                  },
                  new Apartment { Id = 46, SuggestionId = 1, Description = "Test apartment description 46", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 625, BathroomsAmount = 2,
                                  ApartmentSize = 101, IsSmokingAllowed = false, IsSuite = true, Name = "Quintuple Suite Apartment",
                                  },
                  new Apartment { Id = 47, SuggestionId = 15, Description = "Test apartment description 47", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 665, BathroomsAmount = 2,
                                  ApartmentSize = 104, IsSmokingAllowed = false, IsSuite = true, Name = "Quintuple Suite Apartment",
                                  },
                  new Apartment { Id = 48, SuggestionId = 27, Description = "Test apartment description 48", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 225, BathroomsAmount = 2,
                                  ApartmentSize = 108, IsSmokingAllowed = true, IsSuite = true, Name = "Quintuple Suite Apartment",
                                  },
                  new Apartment { Id = 49, SuggestionId = 57, Description = "Test apartment description 49", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 270, BathroomsAmount = 2,
                                  ApartmentSize = 110, IsSmokingAllowed = true, IsSuite = true, Name = "Quintuple Suite Apartment",
                                  },
                  new Apartment { Id = 50, SuggestionId = 101, Description = "Test apartment description 50", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 355, BathroomsAmount = 2,
                                  ApartmentSize = 111, IsSmokingAllowed = false, IsSuite = true, Name = "Quintuple Suite Apartment",
                                  },
                  new Apartment { Id = 51, SuggestionId = 1, Description = "Test apartment description 51", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 45, BathroomsAmount = 1,
                                  ApartmentSize = 60, IsSmokingAllowed = false, IsSuite = false, Name = "Single Studio Apartment",
                                  },
                  new Apartment { Id = 52, SuggestionId = 103, Description = "Test apartment description 52", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 105, BathroomsAmount = 1,
                                  ApartmentSize = 62, IsSmokingAllowed = true, IsSuite = false, Name = "Single Studio Apartment",
                                  },
                  new Apartment { Id = 53, SuggestionId = 27, Description = "Test apartment description 53", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 120, BathroomsAmount = 1,
                                  ApartmentSize = 65, IsSmokingAllowed = true, IsSuite = false, Name = "Single Studio Apartment",
                                  },
                  new Apartment { Id = 54, SuggestionId = 57, Description = "Test apartment description 54", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 70, IsSmokingAllowed = false, IsSuite = false, Name = "Single Studio Apartment",
                                  },
                  new Apartment { Id = 55, SuggestionId = 101, Description = "Test apartment description 55", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 155, BathroomsAmount = 1,
                                  ApartmentSize = 69, IsSmokingAllowed = true, IsSuite = false, Name = "Single Studio Apartment",
                                  },
                  new Apartment { Id = 56, SuggestionId = 1, Description = "Test apartment description 56", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 250, BathroomsAmount = 1,
                                  ApartmentSize = 62, IsSmokingAllowed = true, IsSuite = false, Name = "Double Studio Apartment",
                                  },
                  new Apartment { Id = 57, SuggestionId = 15, Description = "Test apartment description 57", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 150, BathroomsAmount = 1,
                                  ApartmentSize = 73, IsSmokingAllowed = true, IsSuite = false, Name = "Double Studio Apartment",
                                  },
                  new Apartment { Id = 58, SuggestionId = 27, Description = "Test apartment description 58", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 78, IsSmokingAllowed = false, IsSuite = false, Name = "Double Studio Apartment",
                                  },
                  new Apartment { Id = 59, SuggestionId = 57, Description = "Test apartment description 59", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 225, BathroomsAmount = 1,
                                  ApartmentSize = 83, IsSmokingAllowed = true, IsSuite = false, Name = "Double Studio Apartment",
                                  },
                  new Apartment { Id = 60, SuggestionId = 101, Description = "Test apartment description 60", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 355, BathroomsAmount = 1,
                                  ApartmentSize = 85, IsSmokingAllowed = true, IsSuite = false, Name = "Double Studio Apartment",
                                  },
                  new Apartment { Id = 61, SuggestionId = 1, Description = "Test apartment description 61", RoomsAmount = 2,
                                  GuestsLimit = 5, PriceInUSD = 450, BathroomsAmount = 2,
                                  ApartmentSize = 100, IsSmokingAllowed = true, IsSuite = true, Name = "City View King Apartment",
                                  },
                  new Apartment { Id = 62, SuggestionId = 15, Description = "Test apartment description 62", RoomsAmount = 2,
                                  GuestsLimit = 5, PriceInUSD = 400, BathroomsAmount = 3,
                                  ApartmentSize = 110, IsSmokingAllowed = false, IsSuite = true, Name = "City View King Apartment",
                                  },
                  new Apartment { Id = 63, SuggestionId = 27, Description = "Test apartment description 63", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 420, BathroomsAmount = 1,
                                  ApartmentSize = 120, IsSmokingAllowed = false, IsSuite = true, Name = "City View King Apartment",
                                  },
                  new Apartment { Id = 64, SuggestionId = 57, Description = "Test apartment description 64", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 370, BathroomsAmount = 1,
                                  ApartmentSize = 130, IsSmokingAllowed = false, IsSuite = true, Name = "City View King Apartment",
                                  },
                  new Apartment { Id = 65, SuggestionId = 97, Description = "Test apartment description 65", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 360, BathroomsAmount = 2,
                                  ApartmentSize = 135, IsSmokingAllowed = false, IsSuite = true, Name = "City View King Apartment",
                                  },
                  new Apartment { Id = 66, SuggestionId = 1, Description = "Test apartment description 66", RoomsAmount = 2,
                                  GuestsLimit = 5, PriceInUSD = 750, BathroomsAmount = 2,
                                  ApartmentSize = 140, IsSmokingAllowed = true, IsSuite = true, Name = "Panoramic View King Apartment",
                                  },
                  new Apartment { Id = 67, SuggestionId = 15, Description = "Test apartment description 67", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 265, BathroomsAmount = 2,
                                  ApartmentSize = 150, IsSmokingAllowed = true, IsSuite = true, Name = "Panoramic View King Apartment",
                                  },
                  new Apartment { Id = 68, SuggestionId = 27, Description = "Test apartment description 68", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 325, BathroomsAmount = 1,
                                  ApartmentSize = 90, IsSmokingAllowed = false, IsSuite = true, Name = "Panoramic View King Apartment",
                                  },
                  new Apartment { Id = 69, SuggestionId = 57, Description = "Test apartment description 69", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 425, BathroomsAmount = 2,
                                  ApartmentSize = 130, IsSmokingAllowed = false, IsSuite = true, Name = "Panoramic View King Apartment",
                                  },
                  new Apartment { Id = 70, SuggestionId = 101, Description = "Test apartment description 70", RoomsAmount = 2,
                                  GuestsLimit = 5, PriceInUSD = 555, BathroomsAmount = 1,
                                  ApartmentSize = 145, IsSmokingAllowed = true, IsSuite = true, Name = "Panoramic View King Apartment",
                                  },
                  new Apartment { Id = 71, SuggestionId = 7, Description = "Test apartment description 71", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 355, BathroomsAmount = 1,
                                  ApartmentSize = 70, IsSmokingAllowed = true, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 72, SuggestionId = 7, Description = "Test apartment description 72", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 76, IsSmokingAllowed = false, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 73, SuggestionId = 7, Description = "Test apartment description 73", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 65, BathroomsAmount = 1,
                                  ApartmentSize = 86, IsSmokingAllowed = true, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 74, SuggestionId = 7, Description = "Test apartment description 74", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 65, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 75, SuggestionId = 7, Description = "Test apartment description 75", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 425, BathroomsAmount = 2,
                                  ApartmentSize = 130, IsSmokingAllowed = false, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 76, SuggestionId = 7, Description = "Test apartment description 76", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 40, BathroomsAmount = 1,
                                  ApartmentSize = 50, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 77, SuggestionId = 7, Description = "Test apartment description 77", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 52, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 78, SuggestionId = 7, Description = "Test apartment description 78", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 65, BathroomsAmount = 1,
                                  ApartmentSize = 49, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 79, SuggestionId = 7, Description = "Test apartment description 79", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 1125, BathroomsAmount = 2,
                                  ApartmentSize = 137, IsSmokingAllowed = false, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 80, SuggestionId = 7, Description = "Test apartment description 80", RoomsAmount = 2,
                                  GuestsLimit = 4, PriceInUSD = 225, BathroomsAmount = 1,
                                  ApartmentSize = 97, IsSmokingAllowed = true, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 81, SuggestionId = 7, Description = "Test apartment description 81", RoomsAmount = 2,
                                  GuestsLimit = 4, PriceInUSD = 355, BathroomsAmount = 1,
                                  ApartmentSize = 89, IsSmokingAllowed = true, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 82, SuggestionId = 11, Description = "Test apartment description 82", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 30, BathroomsAmount = 1,
                                  ApartmentSize = 87, IsSmokingAllowed = true, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                },
                  new Apartment { Id = 83, SuggestionId = 11, Description = "Test apartment description 83", RoomsAmount = 1,
                                  GuestsLimit = 2, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 68, IsSmokingAllowed = false, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 84, SuggestionId = 11, Description = "Test apartment description 84", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 650, BathroomsAmount = 2,
                                  ApartmentSize = 129, IsSmokingAllowed = false, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 85, SuggestionId = 11, Description = "Test apartment description 85", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 50, BathroomsAmount = 1,
                                  ApartmentSize = 76, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 86, SuggestionId = 11, Description = "Test apartment description 86", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 40, BathroomsAmount = 1,
                                  ApartmentSize = 61, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 87, SuggestionId = 11, Description = "Test apartment description 87", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 870, BathroomsAmount = 2,
                                  ApartmentSize = 136, IsSmokingAllowed = true, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 88, SuggestionId = 11, Description = "Test apartment description 88", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 25, BathroomsAmount = 1,
                                  ApartmentSize = 47, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 89, SuggestionId = 11, Description = "Test apartment description 89", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 85, BathroomsAmount = 1,
                                  ApartmentSize = 76, IsSmokingAllowed = false, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 90, SuggestionId = 11, Description = "Test apartment description 90", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 50, BathroomsAmount = 1,
                                  ApartmentSize = 77, IsSmokingAllowed = false, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 91, SuggestionId = 11, Description = "Test apartment description 91", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 22, BathroomsAmount = 1,
                                  ApartmentSize = 58, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 92, SuggestionId = 33, Description = "Test apartment description 92", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 75, BathroomsAmount = 1,
                                  ApartmentSize = 59, IsSmokingAllowed = true, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 93, SuggestionId = 33, Description = "Test apartment description 93", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 95, BathroomsAmount = 1,
                                  ApartmentSize = 69, IsSmokingAllowed = true, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 94, SuggestionId = 33, Description = "Test apartment description 94", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 100, BathroomsAmount = 1,
                                  ApartmentSize = 69, IsSmokingAllowed = false, IsSuite = true, Name = "One-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 95, SuggestionId = 33, Description = "Test apartment description 95", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 300, BathroomsAmount = 1,
                                  ApartmentSize = 71, IsSmokingAllowed = true, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 96, SuggestionId = 33, Description = "Test apartment description 96", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 650, BathroomsAmount = 3,
                                  ApartmentSize = 152, IsSmokingAllowed = true, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 97, SuggestionId = 33, Description = "Test apartment description 97", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 80, IsSmokingAllowed = true, IsSuite = true, Name = "Two-Bedroom Suite Apartment",
                                  },
                  new Apartment { Id = 98, SuggestionId = 33, Description = "Test apartment description 98", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 125, BathroomsAmount = 1,
                                  ApartmentSize = 78, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 99, SuggestionId = 33, Description = "Test apartment description 99", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 255, BathroomsAmount = 1,
                                  ApartmentSize = 71, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 100, SuggestionId = 33, Description = "Test apartment description 100", RoomsAmount = 4,
                                  GuestsLimit = 5, PriceInUSD = 555, BathroomsAmount = 2,
                                  ApartmentSize = 146, IsSmokingAllowed = false, IsSuite = true, Name = "Queen Apartment",
                                  },
                  new Apartment { Id = 101, SuggestionId = 33, Description = "Test apartment description 101", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 345, BathroomsAmount = 1,
                                  ApartmentSize = 49, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 102, SuggestionId = 33, Description = "Test apartment description 102", RoomsAmount = 2,
                                  GuestsLimit = 1, PriceInUSD = 345, BathroomsAmount = 1,
                                  ApartmentSize = 55, IsSmokingAllowed = false, IsSuite = false, Name = "Single Apartment",
                                  },
                  new Apartment { Id = 103, SuggestionId = 33, Description = "Test apartment description 103", RoomsAmount = 1,
                                  GuestsLimit = 1, PriceInUSD = 365, BathroomsAmount = 1,
                                  ApartmentSize = 56, IsSmokingAllowed = true, IsSuite = false, Name = "Single Apartment",
                                  },
              });
        }
    }
}
