using CloneBookingAPI.Database.Models.Suggestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Database.Configurations.Suggestions
{
    public class ApartmentsConfiguration : IEntityTypeConfiguration<Apartment>
    {
        public void Configure(EntityTypeBuilder<Apartment> builder)
        {
            builder.HasData(
              new Apartment[]
              {
                  new Apartment { Id = 1, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2, 
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 2, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 3, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 4, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 5, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 6, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 7, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 8, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 9, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 10, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 11, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 12, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 13, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 14, SuggestionId = 28, Description = "Test apartment description 28", RoomsAmount = 8,
                                  GuestsLimit = 10, PriceInUSD = 228, PriceInUserCurrency = 2280, BathroomsAmount = 3,},
                  new Apartment { Id = 15, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 16, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 17, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 18, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 19, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 20, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 21, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 22, SuggestionId = 19, Description = "Test apartment description 19", RoomsAmount = 3,
                                  GuestsLimit = 4, PriceInUSD = 55, PriceInUserCurrency = 550, BathroomsAmount = 1,},
                  new Apartment { Id = 23, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 24, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 25, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 26, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 27, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 28, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 29, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 30, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 31, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 32, SuggestionId = 23, Description = "Test apartment description 23", RoomsAmount = 5,
                                  GuestsLimit = 3, PriceInUSD = 75, PriceInUserCurrency = 750, BathroomsAmount = 2,},
                  new Apartment { Id = 33, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 34, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 35, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 36, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 37, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 38, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 39, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 40, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 41, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 42, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 43, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 44, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 45, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 46, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 47, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 48, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 49, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 50, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 51, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 52, SuggestionId = 103, Description = "Test apartment description 103", RoomsAmount = 5,
                                  GuestsLimit = 5, PriceInUSD = 105, PriceInUserCurrency = 1050, BathroomsAmount = 8,},
                  new Apartment { Id = 53, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 54, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 55, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 56, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 57, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 58, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 59, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 60, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
                  new Apartment { Id = 61, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 62, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 63, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 64, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 65, SuggestionId = 97, Description = "Test apartment description 97", RoomsAmount = 2,
                                  GuestsLimit = 2, PriceInUSD = 40, PriceInUserCurrency = 400, BathroomsAmount = 1,},
                  new Apartment { Id = 66, SuggestionId = 1, Description = "Test apartment description 1", RoomsAmount = 2,
                                  GuestsLimit = 3, PriceInUSD = 25, PriceInUserCurrency = 250, BathroomsAmount = 2,},
                  new Apartment { Id = 67, SuggestionId = 15, Description = "Test apartment description 2", RoomsAmount = 3,
                                  GuestsLimit = 5, PriceInUSD = 65, PriceInUserCurrency = 650, BathroomsAmount = 3,},
                  new Apartment { Id = 68, SuggestionId = 27, Description = "Test apartment description 27", RoomsAmount = 4,
                                  GuestsLimit = 8, PriceInUSD = 125, PriceInUserCurrency = 1250, BathroomsAmount = 4,},
                  new Apartment { Id = 69, SuggestionId = 57, Description = "Test apartment description 57", RoomsAmount = 5,
                                  GuestsLimit = 10, PriceInUSD = 225, PriceInUserCurrency = 2250, BathroomsAmount = 5,},
                  new Apartment { Id = 70, SuggestionId = 101, Description = "Test apartment description 101", RoomsAmount = 6,
                                  GuestsLimit = 12, PriceInUSD = 355, PriceInUserCurrency = 3550, BathroomsAmount = 3,},
              });
        }
    }
}
