using CloneBookingAPI.Services.Database.Models;
using CloneBookingAPI.Services.Database.Models.Suggestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;

namespace CloneBookingAPI.Services.Database.Configurations.Suggestions
{
    public class SuggestionsConfiguration : IEntityTypeConfiguration<Suggestion>
    {
        public void Configure(EntityTypeBuilder<Suggestion> builder)
        {
            builder.Property(s => s.StarsRating).HasDefaultValue(0);
            builder.Property(s => s.Progress).HasDefaultValue(0);
            builder.Property(s => s.UniqueCode).HasDefaultValue(string.Empty);

            builder.HasData(
              new Suggestion[]
              {
                  new Suggestion { Id = 1, Name = "Arcadia apartment & sea terrace", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 1",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101001", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 2, Name = "5 room apartment", StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 2",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101002", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 3, Name = "Baron ApartHotel",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 3",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101003", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 4, Name = "Bon Apart",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 4",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101004", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 5, Name = "Plaza Arcadia Apartments",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 5",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101005", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 6, Name = "New apartments in Arcadia sea view",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 6",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101006", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 7, Name = "Royal Loft Primorskiy Boulevard",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 7",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101007", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 8, Name = "Kvartira u samogo moria (GREEN)!", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 8",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101008", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 9, Name = "Royal Arcadia Apartment",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 9",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101009", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 10, Name = "City Rooms Apartments",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 10",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101010", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 11, Name = "RainBow Arkadia Apartment",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 11",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101011", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 12, Name = "Rishelyevskiy",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 12",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101012", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 13, Name = "Lift Hotel Boutique",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 13",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101013", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 14, Name = "Odessa Heart",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 14",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101014", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 15, Name = "Elegia Arcadia Apartments", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 15",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101015", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 16, Name = "Inn Kyiv", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 16",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101016", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 17, Name = "Boutique Apart-Hotel Sherborne", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 17",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101017", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 18, Name = "Na Podole Apartment", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 18",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101018", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 19, Name = "Centre nigh Mariinsky Park Palace", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 19",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101019", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 20, Name = "Apartment On Khreshchatyk 21", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 20",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101020", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 21, Name = "Hotel Lime", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 21",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101021", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 22, Name = "Apartment in Khreshchatyk Passage", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 22",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101022", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 23, Name = "Cosy central Apartment",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 23",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101023", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 24, Name = "Alex Apartments on Lva Tolstogo", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 24",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101024", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 25, Name = "Real Home Apartments",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 25",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101025", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 26, Name = "Hotel \"Mandarin Clubhouse\"", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 26",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101026", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 27, Name = "Bloom Hotel", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 27",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101027", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 28, Name = "Apartment on Sumskaya 46 \"Family\"",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 28",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101028", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 29, Name = "Ameritania at Times Square",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 29",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101029", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 30, Name = "Ace Hotel New York", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 30",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101030", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 31, Name = "NH Collection New York Madison Avenue", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 31",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101031", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 32, Name = "Freehand New York",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 32",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101032", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 33, Name = "Riu Plaza Manhattan Times Square",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 33",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101033", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 34, Name = "Royalton New York",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 34",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101034", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 35, Name = "Hyatt Place New York City/Times Square",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 35",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101035", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 36, Name = "Row NYC at Times Square",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 36",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101036", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 37, Name = "The New Yorker, A Wyndham Hotel",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 37",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101037", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 38, Name = "Motto by Hilton New York City Chelsea", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 38",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101038", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 39, Name = "Element Times Square West", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 39",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101039", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 40, Name = "Doubletree By Hilton New York Times Square West", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 40",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101040", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 41, Name = "Pod Times Square", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 41",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101041", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 42, Name = "DoubleTree by Hilton New York Downtown", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 42",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101042", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 43, Name = "Holiday Inn Express - Times Square South, an IHG Hotel", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 43",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101043", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 44, Name = "West Side YMCA", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 44",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101044", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 45, Name = "Hotel Edison Times Square",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 45",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101045", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 46, Name = "The Carvi Hotel New York, Ascend Hotel Collection", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 46",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101046", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 47, Name = "Riu Plaza New York Times Square", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 47",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101047", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 48, Name = "Pod 51", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 48",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101048", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 49, Name = "Arlo Midtown",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 49",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101049", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 50, Name = "Courtyard by Marriott New York Manhattan/Chelsea", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 50",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101050", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 51, Name = "SpringHill Suites by Marriott New York Manhattan Chelsea", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 51",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101051", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 52, Name = "MADE Hotel",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 52",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101052", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 53, Name = "Sheraton Tribeca New York Hotel",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 53",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101053", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 54, Name = "Hotel Normandie - Los Angeles", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 54",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101054", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 55, Name = "La Quinta by Wyndham LAX", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 55",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101055", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 56, Name = "Los Angeles Airport Marriott",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 56",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101056", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 57, Name = "Magic Castle Hotel", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 57",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101057", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 58, Name = "Holiday Inn Los Angeles - LAX Airport, an IHG Hotel", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 58",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101058", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 59, Name = "Citizen Los Angeles Downtown", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 59",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101059", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 60, Name = "Four Points by Sheraton Los Angeles Westside", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 60",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101060", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 61, Name = "Andaz West Hollywood-a concept by Hyatt",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 61",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101061", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 62, Name = "Four Points by Sheraton Los Angeles International Airport",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 62",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101062", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 63, Name = "The Hollywood Roosevelt", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 63",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101063", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 64, Name = "The Westin Los Angeles Airport", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 64",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101064", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 65, Name = "Hilton Los Angeles Airport", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 65",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101065", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 66, Name = "Hilton Santa Monica",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 66",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101066", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 67, Name = "Sonesta Los Angeles Airport LAX",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 67",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101067", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 68, Name = "Beverly Laurel Hotel", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 68",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101068", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 69, Name = "Hollywood Inn Express South",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 69",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101069", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 70, Name = "Hotel Erwin", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 70",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101070", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 71, Name = "Sheraton Universal", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 71",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101071", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 72, Name = "AIR Venice on the Beach", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 72",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101072", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 73, Name = "Hotel Aventura", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 73",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101073", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 74, Name = "Ramada by Wyndham Los Angeles/Wilshire Center", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 74",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101074", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 75, Name = "Thompson Hollywood", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 75",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101075", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 76, Name = "1 Hotel West Hollywood", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 76",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101076", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 77, Name = "Beverly Hills Marriott", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 77",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101077", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 78, Name = "Avenue Hotel, Ascend Hotel Collection", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 78",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101078", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 79, Name = "Hilton Chicago Magnificent Mile Suites", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 79",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101079", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 80, Name = "Kasa Chicago South Loop", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 80",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101080", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 81, Name = "Home2 Suites By Hilton Chicago River North", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 81",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101081", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 82, Name = "Level Chicago - Old Town", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 82",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101082", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 83, Name = "Hotel Felix", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 83",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101083", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 84, Name = "Sonder South Wabash", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 84",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101084", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 85, Name = "Club Quarters Hotel Central Loop, Chicago", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 85",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101085", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 86, Name = "Pendry Chicago", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 86",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101086", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 87, Name = "River Hotel",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 87",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101087", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 88, Name = "Hotel Julian Chicago", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 88",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101088", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 89, Name = "Homewood Suites by Hilton Chicago-Downtown", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 89",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101089", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 90, Name = "Central Loop Hotel", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 90",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101090", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 91, Name = "Selina Chicago",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 91",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101091", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 92, Name = "Warwick Allerton Chicago", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 92",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101092", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 93, Name = "La Quinta by Wyndham Chicago Downtown", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 93",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101093", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 94, Name = "Congress Plaza Hotel Chicago",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 94",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101094", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 95, Name = "Sonder The Plymouth", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 95",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101095", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 96, Name = "Cambria Hotel Chicago Loop/Theatre District", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 96",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101096", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 97, Name = "The Talbott Hotel",
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 97",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101097", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 98, Name = "Sonder at Grant Park", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 98",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101098", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 99, Name = "Hotel Blake, an Ascend Hotel Collection Member",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 99",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101099", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 100, Name = "The St. Clair Hotel - Magnificent Mile", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 100",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101100", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 101, Name = "Aloft Chicago Mag Mile", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 101",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101101", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 102, Name = "Paddler's Lane Retreat", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 102",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101102", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 103, Name = "The Lodge at Chalk Hill", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 103",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101103", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 104, Name = "Tentrr Signature Site - Trout Meadow",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 104",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101104", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 105, Name = "Microtel Inn & Suites by Wyndham Hazelton/Bruceton Mills", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 105",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101105", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 106, Name = "Cozy Southwind Seven Springs Home, Ski-In and Ski-Out!", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 106",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101106", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 107, Name = "Pristine Resort Townhome 2 Mi to Seven Springs Mtn", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 107",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101107", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 108, Name = "Swiss Mtn Condo 3 Mi to Seven Springs Resort", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 108",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101108", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 109, Name = "The St Gregory Hotel Dupont Circle Georgetown", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 109",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101109", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 110, Name = "Hotel Zena, a Viceroy Urban Retreat", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 110",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101110", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 111, Name = "Riggs Washington DC",
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 111",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101111", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 112, Name = "Club Quarters Hotel White House, Washington DC", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 112",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101112", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 113, Name = "Hotel Harrington", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 113",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101113", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 114, Name = "Beacon Hotel & Corporate Quarters",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 114",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101114", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 115, Name = "Hotel Lombardy", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 115",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101115", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 116, Name = "Wyndham Garden Washington DC North", 
                    StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 116",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1, UniqueCode = "101116", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 117, Name = "Hyatt Place Washington DC/US Capitol", 
                    StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 117",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101117", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 118, Name = "Courtyard by Marriott Washington, DC Dupont Circle", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 118",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101118", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 119, Name = "The Architect",
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 119",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101119", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 120, Name = "The Baron Hotel", 
                    StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 120",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 121, Name = "Hyatt Place Washington DC/US Capitol",
                    StarsRating = 4, Progress = 65, Description = "Test description of test suggestion 121",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101117", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 122, Name = "Courtyard by Marriott Washington, DC Dupont Circle",
                    StarsRating = 5, Progress = 75, Description = "Test description of test suggestion 122",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101118", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 123, Name = "The Architect",
                    StarsRating = 5, Progress = 5, Description = "Test description of test suggestion 123",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101119", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 124, Name = "The Baron Hotel",
                    StarsRating = 5, Progress = 15, Description = "Test description of test suggestion 124",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 125, Name = "Hyatt Place Washington DC/US Capitol",
                    StarsRating = 4, Progress = 25, Description = "Test description of test suggestion 125",
                    IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2, UniqueCode = "101117", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 126, Name = "Courtyard by Marriott Washington, DC Dupont Circle",
                    StarsRating = 5, Progress = 30, Description = "Test description of test suggestion 126",
                    IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, UniqueCode = "101118", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 127, Name = "The Architect",
                    StarsRating = 5, Progress = 35, Description = "Test description of test suggestion 127",
                    IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4, UniqueCode = "101119", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 128, Name = "The Baron Hotel",
                    StarsRating = 5, Progress = 10, Description = "Test description of test suggestion 128",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 129, Name = "The Baron Hotel",
                    StarsRating = 5, Progress = 40, Description = "Test description of test suggestion 129",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 130, Name = "The Baron Hotel",
                    StarsRating = 5, Progress = 45, Description = "Test description of test suggestion 130",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
                  new Suggestion { Id = 131, Name = "The Baron Hotel",
                    StarsRating = 5, Progress = 50, Description = "Test description of test suggestion 131",
                    IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1, UniqueCode = "101120", SuggestionStatusId = 2,
                  },
              });
        }
    }
}
