using CloneBookingAPI.Services.Database.Models;
using CloneBookingAPI.Services.Database.Models.Suggestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;

namespace CloneBookingAPI.Services.Database.Configurations.Suggestions
{
    public class SuggestionsConfiguration : IEntityTypeConfiguration<Suggestion>
    {
        public void Configure(EntityTypeBuilder<Suggestion> builder)
        {
            builder.Property(s => s.Progress).HasDefaultValue(0);
            builder.Property(s => s.UniqueCode).HasDefaultValue(string.Empty);

            builder.HasData(
              new Suggestion[]
              {
                  new Suggestion { Id = 1, Name = "Test Suggestion 1", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 1",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 2, Name = "Test Suggestion 2", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 2",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 3, Name = "Test Suggestion 3", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 3",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, 
                  },
                  new Suggestion { Id = 4, Name = "Test Suggestion 4", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 4",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 5, Name = "Test Suggestion 5", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 5",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 6, Name = "Test Suggestion 6", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 6",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 7, Name = "Test Suggestion 7", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 7",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 8, Name = "Test Suggestion 8", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 8",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 9, Name = "Test Suggestion 9", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 9",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 10, Name = "Test Suggestion 10", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 10",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 11, Name = "Test Suggestion 11", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 11",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 12, Name = "Test Suggestion 12", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 12",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 13, Name = "Test Suggestion 13", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 13",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 14, Name = "Test Suggestion 14", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 14",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 15, Name = "Test Suggestion 15", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 15",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 16, Name = "Test Suggestion 16", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 16",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 17, Name = "Test Suggestion 17", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 17",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 18, Name = "Test Suggestion 18", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 18",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 19, Name = "Test Suggestion 19", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 19",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 20, Name = "Test Suggestion 20", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 20",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 21, Name = "Test Suggestion 21", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 21",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 22, Name = "Test Suggestion 22", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 22",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 23, Name = "Test Suggestion 23", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 23",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 24, Name = "Test Suggestion 24", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 24",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 25, Name = "Test Suggestion 25", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 25",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 26, Name = "Test Suggestion 26", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 26",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 27, Name = "Test Suggestion 27", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 27",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 28, Name = "Test Suggestion 28", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 28",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 29, Name = "Test Suggestion 29", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 29",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 30, Name = "Test Suggestion 30", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 30",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 31, Name = "Test Suggestion 31", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 31",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 32, Name = "Test Suggestion 32", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 32",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 33, Name = "Test Suggestion 33", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 33",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 34, Name = "Test Suggestion 34", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 34",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 35, Name = "Test Suggestion 35", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 35",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 36, Name = "Test Suggestion 36", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 36",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 37, Name = "Test Suggestion 37", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 37",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 38, Name = "Test Suggestion 38", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 38",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 39, Name = "Test Suggestion 39", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 39",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 40, Name = "Test Suggestion 40", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 40",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 41, Name = "Test Suggestion 41", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 41",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 42, Name = "Test Suggestion 42", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 42",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 43, Name = "Test Suggestion 43", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 43",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 44, Name = "Test Suggestion 44", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 44",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 45, Name = "Test Suggestion 45", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 45",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 46, Name = "Test Suggestion 46", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 46",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 47, Name = "Test Suggestion 47", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 47",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 48, Name = "Test Suggestion 48", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 48",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 49, Name = "Test Suggestion 49", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 49",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 50, Name = "Test Suggestion 50", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 50",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 51, Name = "Test Suggestion 51", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 51",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 52, Name = "Test Suggestion 52", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 52",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 53, Name = "Test Suggestion 53", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 53",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 54, Name = "Test Suggestion 54", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 54",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 55, Name = "Test Suggestion 55", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 55",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 56, Name = "Test Suggestion 56", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 56",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 57, Name = "Test Suggestion 57", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 57",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 58, Name = "Test Suggestion 58", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 58",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 59, Name = "Test Suggestion 59", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 59",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 60, Name = "Test Suggestion 60", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 60",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 61, Name = "Test Suggestion 61", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 61",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 62, Name = "Test Suggestion 62", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 62",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 63, Name = "Test Suggestion 63", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 63",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 64, Name = "Test Suggestion 64", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 64",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 65, Name = "Test Suggestion 65", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 65",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 66, Name = "Test Suggestion 66", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 66",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 67, Name = "Test Suggestion 67", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 67",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 68, Name = "Test Suggestion 68", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 68",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 69, Name = "Test Suggestion 69", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 69",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 70, Name = "Test Suggestion 70", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 70",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 71, Name = "Test Suggestion 71", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 71",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 72, Name = "Test Suggestion 72", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 72",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 73, Name = "Test Suggestion 73", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 73",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 74, Name = "Test Suggestion 74", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 74",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 75, Name = "Test Suggestion 75", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 75",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 76, Name = "Test Suggestion 76", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 76",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 77, Name = "Test Suggestion 77", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 77",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 78, Name = "Test Suggestion 78", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 78",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 79, Name = "Test Suggestion 79", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 79",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 80, Name = "Test Suggestion 80", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 80",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 81, Name = "Test Suggestion 81", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 81",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 82, Name = "Test Suggestion 82", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 82",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 83, Name = "Test Suggestion 83", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 83",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 84, Name = "Test Suggestion 84", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 84",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 85, Name = "Test Suggestion 85", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 85",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 86, Name = "Test Suggestion 86", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 86",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 87, Name = "Test Suggestion 87", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 87",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 88, Name = "Test Suggestion 88", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 88",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 89, Name = "Test Suggestion 89", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 89",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 90, Name = "Test Suggestion 90", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 90",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 91, Name = "Test Suggestion 91", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 91",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 92, Name = "Test Suggestion 92", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 92",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 93, Name = "Test Suggestion 93", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 93",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 94, Name = "Test Suggestion 94", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 94",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 95, Name = "Test Suggestion 95", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 95",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 96, Name = "Test Suggestion 96", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 96",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 97, Name = "Test Suggestion 97", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 97",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 98, Name = "Test Suggestion 98", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 98",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 99, Name = "Test Suggestion 99", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 99",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 100, Name = "Test Suggestion 100", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 100",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 101, Name = "Test Suggestion 101", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 101",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 102, Name = "Test Suggestion 102", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 102",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 103, Name = "Test Suggestion 103", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 103",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 104, Name = "Test Suggestion 104", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 104",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 105, Name = "Test Suggestion 105", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 105",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 106, Name = "Test Suggestion 106", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 106",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 107, Name = "Test Suggestion 107", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 107",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 108, Name = "Test Suggestion 108", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 108",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 109, Name = "Test Suggestion 109", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 109",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 110, Name = "Test Suggestion 110", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 110",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 111, Name = "Test Suggestion 111", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 111",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 112, Name = "Test Suggestion 112", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 112",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 113, Name = "Test Suggestion 113", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 113",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 114, Name = "Test Suggestion 114", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 114",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 115, Name = "Test Suggestion 115", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 115",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 116, Name = "Test Suggestion 116", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 116",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 117, Name = "Test Suggestion 117", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 117",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 118, Name = "Test Suggestion 118", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 118",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 119, Name = "Test Suggestion 119", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 119",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 120, Name = "Test Suggestion 120", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 120",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
              });
        }
    }
}
