using CloneBookingAPI.Services.Database.Models;
using CloneBookingAPI.Services.Database.Models.Suggestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;

namespace CloneBookingAPI.Services.Database.Configurations.Suggestions
{
    public class SuggestionsConfiguration : IEntityTypeConfiguration<Suggestion>
    {
        public void Configure(EntityTypeBuilder<Suggestion> builder)
        {
            builder.Property(s => s.Progress).HasDefaultValue(0);
            builder.Property(s => s.UniqueCode).HasDefaultValue(string.Empty);

            builder.HasData(
              new Suggestion[]
              {
                  new Suggestion { Id = 1, Name = "Arcadia apartment & sea terrace", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 1",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 2, Name = "5 room apartment", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 2",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 3, Name = "Baron ApartHotel", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 3",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3, 
                  },
                  new Suggestion { Id = 4, Name = "Bon Apart", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 4",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 5, Name = "Plaza Arcadia Apartments", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 5",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 6, Name = "New apartments in Arcadia sea view", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 6",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 7, Name = "Royal Loft Primorskiy Boulevard", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 7",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 8, Name = "Kvartira u samogo moria (GREEN)!", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 8",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 9, Name = "Royal Arcadia Apartment", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 9",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 10, Name = "City Rooms Apartments", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 10",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 11, Name = "RainBow Arkadia Apartment", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 11",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 12, Name = "Rishelyevskiy", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 12",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 13, Name = "Lift Hotel Boutique", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 13",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 14, Name = "Odessa Heart", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 14",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 15, Name = "Elegia ArCadia Apartments", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 15",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 16, Name = "Inn Kyiv", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 16",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 17, Name = "Boutique Apart-Hotel Sherborne", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 17",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 18, Name = "Na Podole Apartment", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 18",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 19, Name = "Centre nigh Mariinsky Park Palace", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 19",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 20, Name = "Apartment On Khreshchatyk 21", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 20",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 21, Name = "Hotel Lime", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 21",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 22, Name = "Apartment in Khreshchatyk Passage", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 22",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 23, Name = "Cosy central ApartmentOpens in new window", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 23",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 24, Name = "Alex Apartments on Lva Tolstogo", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 24",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 25, Name = "Real Home Apartments", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 25",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 26, Name = "Hotel \"Mandarin Clubhouse\"", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 26",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 27, Name = "Bloom Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 27",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 28, Name = "Apartment on Sumskaya 46 \"Family\"", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 28",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 29, Name = "Ameritania at Times Square", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 29",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 30, Name = "Ace Hotel New York", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 30",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 31, Name = "NH Collection New York Madison Avenue", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 31",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 32, Name = "Freehand New York", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 32",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 33, Name = "Riu Plaza Manhattan Times Square", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 33",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 34, Name = "Royalton New York", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 34",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 35, Name = "Hyatt Place New York City/Times Square", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 35",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 36, Name = "Row NYC at Times Square", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 36",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 37, Name = "The New Yorker, A Wyndham Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 37",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 38, Name = "Motto by Hilton New York City Chelsea", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 38",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 39, Name = "Element Times Square West", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 39",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 40, Name = "Doubletree By Hilton New York Times Square West", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 40",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 41, Name = "Pod Times Square", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 41",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 42, Name = "DoubleTree by Hilton New York Downtown", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 42",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 43, Name = "Holiday Inn Express - Times Square South, an IHG Hotel", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 43",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 44, Name = "West Side YMCA", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 44",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 45, Name = "Hotel Edison Times Square", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 45",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 46, Name = "The Carvi Hotel New York, Ascend Hotel Collection", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 46",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 47, Name = "Riu Plaza New York Times Square", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 47",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 48, Name = "Pod 51", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 48",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 49, Name = "Arlo Midtown", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 49",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 50, Name = "Courtyard by Marriott New York Manhattan/Chelsea", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 50",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 51, Name = "SpringHill Suites by Marriott New York Manhattan Chelsea", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 51",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 52, Name = "MADE Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 52",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 53, Name = "Sheraton Tribeca New York Hotel", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 53",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 54, Name = "Hotel Normandie - Los Angeles", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 54",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 55, Name = "La Quinta by Wyndham LAX", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 55",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 56, Name = "Los Angeles Airport Marriott", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 56",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 57, Name = "Magic Castle Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 57",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 58, Name = "Holiday Inn Los Angeles - LAX Airport, an IHG Hotel", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 58",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 59, Name = "citizenM Los Angeles Downtown", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 59",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 60, Name = "Four Points by Sheraton Los Angeles Westside", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 60",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 61, Name = "Andaz West Hollywood-a concept by Hyatt", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 61",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 62, Name = "Four Points by Sheraton Los Angeles International Airport", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 62",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 63, Name = "The Hollywood Roosevelt", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 63",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 64, Name = "The Westin Los Angeles Airport", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 64",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 65, Name = "Hilton Los Angeles Airport", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 65",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 66, Name = "Hilton Santa Monica", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 66",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 67, Name = "Sonesta Los Angeles Airport LAX", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 67",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 68, Name = "Beverly Laurel Hotel", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 68",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 69, Name = "Hollywood Inn Express South", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 69",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 70, Name = "Hotel Erwin", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 70",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 71, Name = "Sheraton Universal", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 71",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 72, Name = "AIR Venice on the Beach", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 72",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 73, Name = "Hotel Aventura", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 73",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 74, Name = "Ramada by Wyndham Los Angeles/Wilshire Center", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 74",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 75, Name = "Thompson Hollywood", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 75",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 76, Name = "1 Hotel West Hollywood", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 76",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 77, Name = "Beverly Hills Marriott", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 77",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 78, Name = "Avenue Hotel, Ascend Hotel Collection", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 78",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 79, Name = "Hilton Chicago Magnificent Mile Suites", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 79",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 80, Name = "Kasa Chicago South Loop", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 80",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 81, Name = "Home2 Suites By Hilton Chicago River North", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 81",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 82, Name = "Level Chicago - Old Town", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 82",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 83, Name = "Hotel Felix", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 83",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 84, Name = "Sonder South Wabash", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 84",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 85, Name = "Club Quarters Hotel Central Loop, Chicago", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 85",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 86, Name = "Pendry Chicago", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 86",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 87, Name = "River Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 87",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 88, Name = "Hotel Julian Chicago", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 88",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 89, Name = "Homewood Suites by Hilton Chicago-Downtown", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 89",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 90, Name = "Central Loop Hotel", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 90",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 91, Name = "Selina Chicago", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 91",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 92, Name = "Warwick Allerton Chicago", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 92",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 93, Name = "La Quinta by Wyndham Chicago Downtown", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 93",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 94, Name = "Congress Plaza Hotel Chicago", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 94",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 95, Name = "Sonder The Plymouth", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 95",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 96, Name = "Cambria Hotel Chicago Loop/Theatre District", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 96",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 97, Name = "The Talbott Hotel", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 97",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 98, Name = "Sonder at Grant Park", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 98",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 99, Name = "Hotel Blake, an Ascend Hotel Collection Member", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 99",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 100, Name = "The St. Clair Hotel - Magnificent Mile", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 100",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 101, Name = "Aloft Chicago Mag Mile", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 101",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 102, Name = "Paddler's Lane Retreat", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 102",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 103, Name = "The Lodge at Chalk Hill", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 103",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 104, Name = "Tentrr Signature Site - Trout Meadow", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 104",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 105, Name = "Microtel Inn & Suites by Wyndham Hazelton/Bruceton Mills", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 105",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 106, Name = "Cozy Southwind Seven Springs Home, Ski-In and Ski-Out!", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 106",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 107, Name = "Pristine Resort Townhome 2 Mi to Seven Springs Mtn", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 107",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 108, Name = "Swiss Mtn Condo 3 Mi to Seven Springs Resort", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 108",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 109, Name = "The St Gregory Hotel Dupont Circle Georgetown", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 109",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 110, Name = "Hotel Zena, a Viceroy Urban Retreat", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 110",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 111, Name = "Riggs Washington DC", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 111",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 112, Name = "Club Quarters Hotel White House, Washington DC", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 112",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 113, Name = "Hotel Harrington", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 113",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 114, Name = "Beacon Hotel & Corporate Quarters", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 114",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 115, Name = "Hotel Lombardy", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 115",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
                  new Suggestion { Id = 116, Name = "Wyndham Garden Washington DC North", GuestsAmount = 2, BathroomsAmount = 1,
                    RoomsAmount = 3, StarsRating = 3, Progress = 100, Description = "Test description of test suggestion 116",
                    PriceInUserCurrency = 10121, PriceInUSD = 25, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 1, AddressId = 1,
                  },
                  new Suggestion { Id = 117, Name = "Hyatt Place Washington DC/US Capitol", GuestsAmount = 1, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 4, Progress = 100, Description = "Test description of test suggestion 117",
                    PriceInUserCurrency = 1010, PriceInUSD = 55, IsParkingAvailable = false, UserId = 2, ServiceCategoryId = 1,
                    BookingCategoryId = 2, AddressId = 2,
                  },
                  new Suggestion { Id = 118, Name = "Courtyard by Marriott Washington, DC Dupont Circle", GuestsAmount = 5, BathroomsAmount = 2,
                    RoomsAmount = 5, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 118",
                    PriceInUserCurrency = 2032, PriceInUSD = 155, IsParkingAvailable = true, UserId = 3, ServiceCategoryId = 1,
                    BookingCategoryId = 3, AddressId = 3,
                  },
                  new Suggestion { Id = 119, Name = "The Architect", GuestsAmount = 4, BathroomsAmount = 2,
                    RoomsAmount = 4, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 119",
                    PriceInUserCurrency = 2100, PriceInUSD = 255, IsParkingAvailable = true, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 4, AddressId = 4,
                  },
                  new Suggestion { Id = 120, Name = "The Baron Hotel", GuestsAmount = 3, BathroomsAmount = 3,
                    RoomsAmount = 6, StarsRating = 5, Progress = 100, Description = "Test description of test suggestion 120",
                    PriceInUserCurrency = 1905, PriceInUSD = 355, IsParkingAvailable = false, UserId = 1, ServiceCategoryId = 1,
                    BookingCategoryId = 5, AddressId = 1,
                  },
              });
        }
    }
}
