using CloneBookingAPI.Services.Database.Models.Location;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Services.Database.Configurations.Location
{
    public class CitiesConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.HasData(
              new City[]
              {
                  new City { Id = 1, Title = "Odesa", ImageId = 41, CountryId = 1, },
                  new City { Id = 2, Title = "Kharkiv", ImageId = 42, CountryId = 1, },
                  new City { Id = 3, Title = "Dnipro", ImageId = 43, CountryId = 1, },
                  new City { Id = 4, Title = "Donetsk", ImageId = 44, CountryId = 1, },
                  new City { Id = 5, Title = "Lviv", ImageId = 45, CountryId = 1, },
                  new City { Id = 6, Title = "Zaporizhzhia", ImageId = 46, CountryId = 1, },
                  new City { Id = 7, Title = "Kryvyi Rih", ImageId = 47, CountryId = 1, },
                  new City { Id = 8, Title = "Mykolaiv", ImageId = 48, CountryId = 1, },
                  new City { Id = 9, Title = "Sevastopol", ImageId = 49, CountryId = 1, },
                  new City { Id = 10, Title = "Mariupol", ImageId = 50, CountryId = 1, },
                  new City { Id = 11, Title = "Luhansk", ImageId = 51, CountryId = 1, },
                  new City { Id = 12, Title = "Vinnytsia", ImageId = 52, CountryId = 1, },
                  new City { Id = 13, Title = "Makiivka", ImageId = 53, CountryId = 1, },
                  new City { Id = 14, Title = "Simferopol", ImageId = 54, CountryId = 1, },
                  new City { Id = 15, Title = "Chernihiv", ImageId = 55, CountryId = 1, },
                  new City { Id = 16, Title = "Kherson", ImageId = 56, CountryId = 1, },
                  new City { Id = 17, Title = "Poltava", ImageId = 57, CountryId = 1, },
                  new City { Id = 18, Title = "Khmelnytskyi", ImageId = 58, CountryId = 1, },
                  new City { Id = 19, Title = "Cherkasy", ImageId = 59, CountryId = 1, },
                  new City { Id = 20, Title = "Chernivtsi", ImageId = 60, CountryId = 1, },
                  new City { Id = 21, Title = "Zhytomyr", ImageId = 61, CountryId = 1, },
                  new City { Id = 22, Title = "Sumy", ImageId = 62, CountryId = 1, },
                  new City { Id = 23, Title = "Rivne", ImageId = 63, CountryId = 1, },
                  new City { Id = 24, Title = "Horlivka", ImageId = 64, CountryId = 1, },
                  new City { Id = 25, Title = "Ivano-Frankivsk", ImageId = 65, CountryId = 1, },
                  new City { Id = 26, Title = "Kamianske", ImageId = 66, CountryId = 1, },
                  new City { Id = 27, Title = "Ternopil", ImageId = 67, CountryId = 1, },
                  new City { Id = 28, Title = "Kropyvnytskyi", ImageId = 68, CountryId = 1, },
                  new City { Id = 29, Title = "Kremenchuk", ImageId = 69, CountryId = 1, },
                  new City { Id = 30, Title = "Lutsk", ImageId = 70, CountryId = 1, },
                  new City { Id = 31, Title = "Bila Tserkva", ImageId = 71, CountryId = 1, },
                  new City { Id = 32, Title = "Kerch", ImageId = 72, CountryId = 1, },
                  new City { Id = 33, Title = "Melitopol", ImageId = 73, CountryId = 1, },
                  new City { Id = 34, Title = "Kramatorsk", ImageId = 74, CountryId = 1, },
                  new City { Id = 35, Title = "Uzhhorod", ImageId = 75, CountryId = 1, },
                  new City { Id = 36, Title = "Brovary", ImageId = 76, CountryId = 1, },
                  new City { Id = 37, Title = "Yevpatoria", ImageId = 77, CountryId = 1, },
                  new City { Id = 38, Title = "Berdiansk", ImageId = 78, CountryId = 1, },
                  new City { Id = 39, Title = "Nikopol", ImageId = 79, CountryId = 1, },
                  new City { Id = 40, Title = "Sloviansk", ImageId = 80, CountryId = 1, },
                  new City { Id = 41, Title = "Alchevsk", ImageId = 81, CountryId = 1, },
                  new City { Id = 42, Title = "Pavlohrad", ImageId = 82, CountryId = 1, },
                  new City { Id = 43, Title = "Sievierodonetsk", ImageId = 83, CountryId = 1, },
                  new City { Id = 44, Title = "Kamianets-Podilskyi", ImageId = 84, CountryId = 1, },
                  new City { Id = 45, Title = "Lysychansk", ImageId = 85, CountryId = 1, },
                  new City { Id = 46, Title = "Mukachevo", ImageId = 86, CountryId = 1, },
                  new City { Id = 47, Title = "Konotop", ImageId = 87, CountryId = 1, },
                  new City { Id = 48, Title = "Uman", ImageId = 88, CountryId = 1, },
                  new City { Id = 49, Title = "New York", ImageId = 1, CountryId = 2, },
                  new City { Id = 50, Title = "Los Angeles", ImageId = 1, CountryId = 2, },
                  new City { Id = 51, Title = "Chicago", ImageId = 1, CountryId = 2, },
                  new City { Id = 52, Title = "Houston", ImageId = 1, CountryId = 2, },
                  new City { Id = 53, Title = "Phoenix", ImageId = 1, CountryId = 2, },
                  new City { Id = 54, Title = "Philadelphia", ImageId = 1, CountryId = 2, },
                  new City { Id = 55, Title = "San Antonio", ImageId = 1, CountryId = 2, },
                  new City { Id = 56, Title = "San Diego", ImageId = 1, CountryId = 2, },
                  new City { Id = 57, Title = "Dallas", ImageId = 1, CountryId = 2, },
                  new City { Id = 58, Title = "San Jose", ImageId = 1, CountryId = 2, },
                  new City { Id = 59, Title = "Austin", ImageId = 1, CountryId = 2, },
                  new City { Id = 60, Title = "Jacksonville", ImageId = 1, CountryId = 2, },
                  new City { Id = 61, Title = "Fort Worth", ImageId = 1, CountryId = 2, },
                  new City { Id = 62, Title = "Columbus", ImageId = 1, CountryId = 2, },
                  new City { Id = 63, Title = "Indianapolis", ImageId = 1, CountryId = 2, },
                  new City { Id = 64, Title = "Charlotte", ImageId = 1, CountryId = 2, },
                  new City { Id = 65, Title = "San Francisco", ImageId = 1, CountryId = 2, },
                  new City { Id = 66, Title = "Seattle", ImageId = 1, CountryId = 2, },
                  new City { Id = 67, Title = "Denver", ImageId = 1, CountryId = 2, },
                  new City { Id = 68, Title = "Washington", ImageId = 1, CountryId = 2, },
                  new City { Id = 69, Title = "Nashville[", ImageId = 1, CountryId = 2, },
                  new City { Id = 70, Title = "Oklahoma City", ImageId = 1, CountryId = 2, },
                  new City { Id = 71, Title = "El Paso", ImageId = 1, CountryId = 2, },
                  new City { Id = 72, Title = "Boston", ImageId = 1, CountryId = 2, },
                  new City { Id = 73, Title = "Portland", ImageId = 1, CountryId = 2, },
                  new City { Id = 74, Title = "Las Vegas", ImageId = 1, CountryId = 2, },
                  new City { Id = 75, Title = "Detroit", ImageId = 1, CountryId = 2, },
                  new City { Id = 76, Title = "Memphis", ImageId = 1, CountryId = 2, },
                  new City { Id = 77, Title = "Louisville[", ImageId = 1, CountryId = 2, },
                  new City { Id = 78, Title = "Baltimore", ImageId = 1, CountryId = 2, },
                  new City { Id = 79, Title = "Milwaukee", ImageId = 1, CountryId = 2, },
                  new City { Id = 80, Title = "Sacramento", ImageId = 1, CountryId = 2, },
                  new City { Id = 81, Title = "Atlanta", ImageId = 1, CountryId = 2, },
                  new City { Id = 82, Title = "Honolulu", ImageId = 1, CountryId = 2, },
                  new City { Id = 83, Title = "London", ImageId = 3, CountryId = 3, },
                  new City { Id = 84, Title = "Birmingham", ImageId = 3, CountryId = 3, },
                  new City { Id = 85, Title = "Leeds", ImageId = 3, CountryId = 3, },
                  new City { Id = 86, Title = "Glasgow", ImageId = 3, CountryId = 3, },
                  new City { Id = 87, Title = "Sheffield", ImageId = 3, CountryId = 3, },
                  new City { Id = 88, Title = "Bradford", ImageId = 3, CountryId = 3, },
                  new City { Id = 89, Title = "Liverpool", ImageId = 3, CountryId = 3, },
                  new City { Id = 90, Title = "Edinburgh", ImageId = 3, CountryId = 3, },
                  new City { Id = 91, Title = "Manchester", ImageId = 3, CountryId = 3, },
                  new City { Id = 92, Title = "Bristol", ImageId = 3, CountryId = 3, },
                  new City { Id = 93, Title = "Kirklees", ImageId = 3, CountryId = 3, },
                  new City { Id = 94, Title = "Fife", ImageId = 3, CountryId = 3, },
                  new City { Id = 95, Title = "Wirral", ImageId = 3, CountryId = 3, },
                  new City { Id = 96, Title = "North Lanarkshire", ImageId = 3, CountryId = 3, },
                  new City { Id = 97, Title = "Wakefield", ImageId = 3, CountryId = 3, },
                  new City { Id = 98, Title = "Cardiff", ImageId = 3, CountryId = 3, },
                  new City { Id = 99, Title = "Dudley", ImageId = 3, CountryId = 3, },
                  new City { Id = 100, Title = "Wigan", ImageId = 3, CountryId = 3, },
                  new City { Id = 101, Title = "Istanbul", ImageId = 4, CountryId = 49, },
                  new City { Id = 102, Title = "Ankara", ImageId = 4, CountryId = 49, },
                  new City { Id = 103, Title = "İzmir", ImageId = 4, CountryId = 49, },
                  new City { Id = 104, Title = "Bursa", ImageId = 4, CountryId = 49, },
                  new City { Id = 105, Title = "Adana", ImageId = 4, CountryId = 49, },
                  new City { Id = 106, Title = "Gaziantep", ImageId = 4, CountryId = 49, },
                  new City { Id = 107, Title = "Konya", ImageId = 4, CountryId = 49, },
                  new City { Id = 108, Title = "Antalya", ImageId = 4, CountryId = 49, },
                  new City { Id = 109, Title = "Kayseri", ImageId = 4, CountryId = 49, },
                  new City { Id = 110, Title = "Mersin", ImageId = 4, CountryId = 49, },
                  new City { Id = 111, Title = "Eskişehir", ImageId = 4, CountryId = 49, },
                  new City { Id = 112, Title = "Diyarbakır", ImageId = 4, CountryId = 49, },
                  new City { Id = 113, Title = "Budapest", ImageId = 5, CountryId = 10, },
                  new City { Id = 114, Title = "Debrecen", ImageId = 5, CountryId = 10, },
                  new City { Id = 115, Title = "Szeged", ImageId = 5, CountryId = 10, },
                  new City { Id = 116, Title = "Miskolc", ImageId = 5, CountryId = 10, },
                  new City { Id = 117, Title = "Pécs", ImageId = 5, CountryId = 10, },
                  new City { Id = 118, Title = "Rome", ImageId = 6, CountryId = 60, },
                  new City { Id = 119, Title = "Milan", ImageId = 6, CountryId = 60, },
                  new City { Id = 120, Title = "Naples", ImageId = 6, CountryId = 60, },
                  new City { Id = 121, Title = "Turin", ImageId = 6, CountryId = 60, },
                  new City { Id = 122, Title = "Palermo", ImageId = 6, CountryId = 60, },
                  new City { Id = 123, Title = "Genoa", ImageId = 6, CountryId = 60, },
                  new City { Id = 124, Title = "Stockholm", ImageId = 7, CountryId = 64, },
                  new City { Id = 125, Title = "Gothenburg", ImageId = 7, CountryId = 64, },
                  new City { Id = 126, Title = "Malmö", ImageId = 7, CountryId = 64, },
                  new City { Id = 127, Title = "Uppsala", ImageId = 7, CountryId = 64, },
                  new City { Id = 128, Title = "Västerås", ImageId = 7, CountryId = 64, },
                  new City { Id = 129, Title = "Oslo", ImageId = 8, CountryId = 63, },
                  new City { Id = 130, Title = "Drammen", ImageId = 8, CountryId = 63, },
                  new City { Id = 131, Title = "Trondheim", ImageId = 8, CountryId = 63, },
                  new City { Id = 132, Title = "Kristiansand", ImageId = 8, CountryId = 63, },
                  new City { Id = 133, Title = "Stavanger", ImageId = 8, CountryId = 63, },
                  new City { Id = 134, Title = "Madrid", ImageId = 9, CountryId = 72, },
                  new City { Id = 135, Title = "Barcelona", ImageId = 9, CountryId = 72, },
                  new City { Id = 136, Title = "Valencia", ImageId = 9, CountryId = 72, },
                  new City { Id = 137, Title = "Sevilla", ImageId = 9, CountryId = 72, },
                  new City { Id = 138, Title = "Zaragoza", ImageId = 9, CountryId = 72, },
                  new City { Id = 139, Title = "Athens", ImageId = 10, CountryId = 80, },
                  new City { Id = 140, Title = "Thessaloniki", ImageId = 10, CountryId = 80, },
                  new City { Id = 141, Title = "Patra", ImageId = 10, CountryId = 80, },
                  new City { Id = 142, Title = "Piraeus", ImageId = 10, CountryId = 80, },
                  new City { Id = 143, Title = "Larisa", ImageId = 10, CountryId = 80, },
                  new City { Id = 144, Title = "Jerusalem", ImageId = 11, CountryId = 113, },
                  new City { Id = 145, Title = "Tel Aviv", ImageId = 11, CountryId = 113, },
                  new City { Id = 146, Title = "West Jerusalem", ImageId = 11, CountryId = 113, },
                  new City { Id = 147, Title = "Haifa", ImageId = 11, CountryId = 113, },
                  new City { Id = 148, Title = "Ashdod", ImageId = 11, CountryId = 113, },
                  new City { Id = 149, Title = "Berlin", ImageId = 12, CountryId = 114, },
                  new City { Id = 150, Title = "Hamburg", ImageId = 12, CountryId = 114, },
                  new City { Id = 151, Title = "München", ImageId = 12, CountryId = 114, },
                  new City { Id = 152, Title = "Köln", ImageId = 12, CountryId = 114, },
                  new City { Id = 153, Title = "Frankfurt", ImageId = 12, CountryId = 114, },
                  new City { Id = 154, Title = "Paris", ImageId = 13, CountryId = 123, },
                  new City { Id = 155, Title = "Marseille", ImageId = 13, CountryId = 123, },
                  new City { Id = 156, Title = "Lyon", ImageId = 13, CountryId = 123, },
                  new City { Id = 157, Title = "Toulouse", ImageId = 13, CountryId = 123, },
                  new City { Id = 158, Title = "Nice", ImageId = 13, CountryId = 123, },
                  new City { Id = 159, Title = "Sydney", ImageId = 14, CountryId = 130, },
                  new City { Id = 160, Title = "Melbourne", ImageId = 14, CountryId = 130, },
                  new City { Id = 161, Title = "Brisbane", ImageId = 14, CountryId = 130, },
                  new City { Id = 162, Title = "Perth", ImageId = 14, CountryId = 130, },
                  new City { Id = 163, Title = "Adelaide ", ImageId = 14, CountryId = 130, },
                  new City { Id = 164, Title = "Toronto", ImageId = 15, CountryId = 129, },
                  new City { Id = 165, Title = "Montréal", ImageId = 15, CountryId = 129, },
                  new City { Id = 166, Title = "Vancouver", ImageId = 15, CountryId = 129, },
                  new City { Id = 167, Title = "Calgary", ImageId = 15, CountryId = 129, },
                  new City { Id = 168, Title = "Edmonton", ImageId = 15, CountryId = 129, },
                  new City { Id = 169, Title = "Tokyo", ImageId = 16, CountryId = 135, },
                  new City { Id = 170, Title = "Yokohama", ImageId = 16, CountryId = 135, },
                  new City { Id = 171, Title = "Osaka", ImageId = 16, CountryId = 135, },
              });
        }
    }
}
