using CloneBookingAPI.Services.Database.Models.Location;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Services.Database.Configurations.Location
{
    public class CountriesConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
              new Country[]
              {
                  new Country { Id = 1, Title = "Ukraine", ImageId = 1 },
                  new Country { Id = 2, Title = "USA", ImageId = 2 },
                  new Country { Id = 3, Title = "UK", ImageId = 3 },
                  new Country { Id = 4, Title = "Belarus", ImageId = 1 },
                  new Country { Id = 5, Title = "Bosnia and Herzegovina", ImageId = 1 },
                  new Country { Id = 6, Title = "Algeria", ImageId = 1 },
                  new Country { Id = 7, Title = "Chad", ImageId = 1 },
                  new Country { Id = 8, Title = "Czech Republic", ImageId = 1 },
                  new Country { Id = 9, Title = "French Polynesia", ImageId = 1 },
                  new Country { Id = 10, Title = "Hungary", ImageId = 5 },
                  new Country { Id = 11, Title = "Gabon", ImageId = 1 },
                  new Country { Id = 12, Title = "Iraq", ImageId = 1 },
                  new Country { Id = 13, Title = "Madagascar", ImageId = 1 },
                  new Country { Id = 14, Title = "Namibia", ImageId = 1 },
                  new Country { Id = 15, Title = "Lithuania", ImageId = 1 },
                  new Country { Id = 16, Title = "Niue", ImageId = 1 },
                  new Country { Id = 17, Title = "Nigeria", ImageId = 1 },
                  new Country { Id = 18, Title = "Oman", ImageId = 1 },
                  new Country { Id = 19, Title = "Saint Kitts and Nevis", ImageId = 1 },
                  new Country { Id = 20, Title = "San Marino", ImageId = 1 },
                  new Country { Id = 21, Title = "Russia", ImageId = 1 },
                  new Country { Id = 22, Title = "Seychelles", ImageId = 1 },
                  new Country { Id = 23, Title = "Sri Lanka", ImageId = 1 },
                  new Country { Id = 24, Title = "Senegal", ImageId = 1 },
                  new Country { Id = 25, Title = "Trinidad and Tobago", ImageId = 1 },
                  new Country { Id = 26, Title = "Uruguay", ImageId = 1 },
                  new Country { Id = 27, Title = "Uzbekistan", ImageId = 1 },
                  new Country { Id = 28, Title = "Montenegro", ImageId = 1 },
                  new Country { Id = 29, Title = "Saint Barts", ImageId = 1 },
                  new Country { Id = 30, Title = "Albania", ImageId = 1 },
                  new Country { Id = 31, Title = "Andorra", ImageId = 1 },
                  new Country { Id = 32, Title = "Botswana", ImageId = 1 },
                  new Country { Id = 33, Title = "Burundi", ImageId = 1 },
                  new Country { Id = 34, Title = "Denmark", ImageId = 1 },
                  new Country { Id = 35, Title = "China", ImageId = 1 },
                  new Country { Id = 36, Title = "Cape Verde", ImageId = 1 },
                  new Country { Id = 37, Title = "Ecuador", ImageId = 1 },
                  new Country { Id = 38, Title = "India", ImageId = 1 },
                  new Country { Id = 39, Title = "Lebanon", ImageId = 1 },
                  new Country { Id = 40, Title = "Malaysia", ImageId = 1 },
                  new Country { Id = 41, Title = "Nepal", ImageId = 1 },
                  new Country { Id = 42, Title = "Liechtenstein", ImageId = 1 },
                  new Country { Id = 43, Title = "Paraguay", ImageId = 1 },
                  new Country { Id = 44, Title = "Portugal", ImageId = 1 },
                  new Country { Id = 45, Title = "Saint Vincent & Grenadines", ImageId = 1 },
                  new Country { Id = 46, Title = "Saudi Arabia", ImageId = 1 },
                  new Country { Id = 47, Title = "Tanzania", ImageId = 1 },
                  new Country { Id = 48, Title = "Tonga", ImageId = 1 },
                  new Country { Id = 49, Title = "Turkey", ImageId = 4 },
                  new Country { Id = 50, Title = "Uganda", ImageId = 1 },
                  new Country { Id = 51, Title = "Venezuela", ImageId = 1 },
                  new Country { Id = 52, Title = "Argentina", ImageId = 1 },
                  new Country { Id = 53, Title = "Azerbaijan", ImageId = 1 },
                  new Country { Id = 54, Title = "Bhutan", ImageId = 1 },
                  new Country { Id = 55, Title = "Burkina Faso", ImageId = 1 },
                  new Country { Id = 56, Title = "Ivory Coast", ImageId = 1 },
                  new Country { Id = 57, Title = "Cyprus", ImageId = 1 },
                  new Country { Id = 58, Title = "Guadeloupe", ImageId = 1 },
                  new Country { Id = 59, Title = "Indonesia", ImageId = 1 },
                  new Country { Id = 60, Title = "Italy", ImageId = 6 },
                  new Country { Id = 61, Title = "Moldova", ImageId = 1 },
                  new Country { Id = 62, Title = "Myanmar", ImageId = 1 },
                  new Country { Id = 63, Title = "Norway", ImageId = 8 },
                  new Country { Id = 64, Title = "Sweden", ImageId = 7 },
                  new Country { Id = 65, Title = "Togo", ImageId = 1 },
                  new Country { Id = 66, Title = "Vanuatu", ImageId = 1 },
                  new Country { Id = 67, Title = "Curaçao", ImageId = 1 },
                  new Country { Id = 68, Title = "Bahrain", ImageId = 1 },
                  new Country { Id = 69, Title = "Gambia", ImageId = 1 },
                  new Country { Id = 70, Title = "Kenya", ImageId = 1 },
                  new Country { Id = 71, Title = "Laos", ImageId = 1 },
                  new Country { Id = 72, Title = "Spain", ImageId = 9 },
                  new Country { Id = 73, Title = "Anguilla", ImageId = 1 },
                  new Country { Id = 74, Title = "Dominica", ImageId = 1 },
                  new Country { Id = 75, Title = "Mauritius", ImageId = 1 },
                  new Country { Id = 76, Title = "Nicaragua", ImageId = 1 },
                  new Country { Id = 77, Title = "Bolivia", ImageId = 1 },
                  new Country { Id = 78, Title = "Colombia", ImageId = 1 },
                  new Country { Id = 79, Title = "Croatia", ImageId = 1 },
                  new Country { Id = 80, Title = "Greece", ImageId = 10 },
                  new Country { Id = 81, Title = "Martinique", ImageId = 1 },
                  new Country { Id = 82, Title = "Philippines", ImageId = 1 },
                  new Country { Id = 83, Title = "United Kingdom", ImageId = 1 },
                  new Country { Id = 84, Title = "St. Maarten", ImageId = 1 },
                  new Country { Id = 85, Title = "Belize", ImageId = 1 },
                  new Country { Id = 86, Title = "Chile", ImageId = 1 },
                  new Country { Id = 87, Title = "Ethiopia", ImageId = 1 },
                  new Country { Id = 88, Title = "Greenland", ImageId = 1 },
                  new Country { Id = 89, Title = "Morocco", ImageId = 1 },
                  new Country { Id = 90, Title = "Samoa", ImageId = 1 },
                  new Country { Id = 91, Title = "Cambodia", ImageId = 1 },
                  new Country { Id = 92, Title = "Cook Islands", ImageId = 1 },
                  new Country { Id = 93, Title = "Egypt", ImageId = 1 },
                  new Country { Id = 94, Title = "Ghana", ImageId = 1 },
                  new Country { Id = 95, Title = "Guyana", ImageId = 1 },
                  new Country { Id = 96, Title = "Netherlands", ImageId = 1 },
                  new Country { Id = 97, Title = "Romania", ImageId = 1 },
                  new Country { Id = 98, Title = "Malta", ImageId = 1 },
                  new Country { Id = 99, Title = "Ireland", ImageId = 1 },
                  new Country { Id = 100, Title = "Solomon Islands", ImageId = 1 },
                  new Country { Id = 101, Title = "Taiwan", ImageId = 1 },
                  new Country { Id = 102, Title = "Saint Martin", ImageId = 1 },
                  new Country { Id = 103, Title = "Barbados", ImageId = 1 },
                  new Country { Id = 104, Title = "Belgium", ImageId = 1 },
                  new Country { Id = 105, Title = "Jamaica", ImageId = 1 },
                  new Country { Id = 106, Title = "Maldives", ImageId = 1 },
                  new Country { Id = 107, Title = "Switzerland", ImageId = 1 },
                  new Country { Id = 108, Title = "Fiji", ImageId = 1 },
                  new Country { Id = 109, Title = "South Africa", ImageId = 1 },
                  new Country { Id = 110, Title = "Turks & Caicos Islands", ImageId = 1 },
                  new Country { Id = 111, Title = "Bermuda", ImageId = 1 },
                  new Country { Id = 112, Title = "El Salvador", ImageId = 1 },
                  new Country { Id = 113, Title = "Israel", ImageId = 11 },
                  new Country { Id = 114, Title = "Germany", ImageId = 12 },
                  new Country { Id = 115, Title = "Monaco", ImageId = 1 },
                  new Country { Id = 116, Title = "Qatar", ImageId = 1 },
                  new Country { Id = 117, Title = "Thailand", ImageId = 1 },
                  new Country { Id = 118, Title = "Dominican Republic", ImageId = 1 },
                  new Country { Id = 119, Title = "Cayman Islands", ImageId = 1 },
                  new Country { Id = 120, Title = "Saint Lucia", ImageId = 1 },
                  new Country { Id = 121, Title = "Panama", ImageId = 1 },
                  new Country { Id = 122, Title = "Vietnam", ImageId = 1 },
                  new Country { Id = 123, Title = "France", ImageId = 13 },
                  new Country { Id = 124, Title = "South Korea", ImageId = 1 },
                  new Country { Id = 125, Title = "Iceland", ImageId = 1 },
                  new Country { Id = 126, Title = "New Zealand", ImageId = 1 },
                  new Country { Id = 127, Title = "Costa Rica", ImageId = 1 },
                  new Country { Id = 128, Title = "Faroe Islands", ImageId = 1 },
                  new Country { Id = 129, Title = "Canada", ImageId = 15 },
                  new Country { Id = 130, Title = "Australia", ImageId = 14 },
                  new Country { Id = 131, Title = "Guam", ImageId = 1 },
                  new Country { Id = 132, Title = "U.S. Virgin Islands", ImageId = 1 },
                  new Country { Id = 133, Title = "Bahamas", ImageId = 1 },
                  new Country { Id = 134, Title = "Haiti", ImageId = 1 },
                  new Country { Id = 135, Title = "Japan", ImageId = 16 },
                  new Country { Id = 136, Title = "Aruba", ImageId = 1 },
                  new Country { Id = 137, Title = "Puerto Rico", ImageId = 1 },
              });
        }
    }
}
