using CloneBookingAPI.Services.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CloneBookingAPI.Services.Database.Configurations
{
    public class FileModelConfiguration : IEntityTypeConfiguration<FileModel>
    {
        public void Configure(EntityTypeBuilder<FileModel> builder)
        {
            builder.HasData(
              new FileModel[]
              {
                  new FileModel { Id = 1, Name = "YSJu1Nj3YEKYuc+MC4TSlRWPvtybYtnfFT6dHXPt5k=.png", Path = "/files/YSJu1Nj3YEKYuc+MC4TSlRWPvtybYtnfFT6dHXPt5k=.png", },
                  new FileModel { Id = 2, Name = "N6TTPt7raEBYeOcLAFMjL1mWb5ip+Kt9YXHddBJ5+A=.png", Path = "/files/N6TTPt7raEBYeOcLAFMjL1mWb5ip+Kt9YXHddBJ5+A=.png", },
                  new FileModel { Id = 3, Name = "AyFnP96S870Z5dpsREvobcCqkk9WxRqZaqrlwDD+aU=.png", Path = "/files/AyFnP96S870Z5dpsREvobcCqkk9WxRqZaqrlwDD+aU=.png", },
                  new FileModel { Id = 4, Name = "PMPvpvziKwjaiBm+NJOnumepEhpdkEpmwZX+y8uGxM=.png", Path = "/files/PMPvpvziKwjaiBm+NJOnumepEhpdkEpmwZX+y8uGxM=.png", },
                  new FileModel { Id = 5, Name = "JonaGiXS6Fy5vFAhFXV6yi4gF0QAjlGfAKt1tLfNH4=.png", Path = "/files/JonaGiXS6Fy5vFAhFXV6yi4gF0QAjlGfAKt1tLfNH4=.png", },
                  new FileModel { Id = 6, Name = "hunLamNewdFFiIJuD2jTaHhnD62OU2EwqFp4lao+qNY=.png", Path = "/files/hunLamNewdFFiIJuD2jTaHhnD62OU2EwqFp4lao+qNY=.png", },
                  new FileModel { Id = 7, Name = "U4h32cGZhMmt59xHBhyIkx+2qJ6x2cs+23U9c94ugcc=.png", Path = "/files/U4h32cGZhMmt59xHBhyIkx+2qJ6x2cs+23U9c94ugcc=.png", },
                  new FileModel { Id = 8, Name = "89NTq1CzGc3AnN8+m2RNyIzkfP33nOm96VYeeoJmbBQ=.png", Path = "/files/89NTq1CzGc3AnN8+m2RNyIzkfP33nOm96VYeeoJmbBQ=.png", },
                  new FileModel { Id = 9, Name = "H8v3dNgasrnuIthKRth17pFIb+3bfi7j09YDODmk4l4=.png", Path = "/files/H8v3dNgasrnuIthKRth17pFIb+3bfi7j09YDODmk4l4=.png", },
                  new FileModel { Id = 10, Name = "pBWV7R2w3omzP+Kv5PxT627LiqV3evixcVyN4B9NovI=.png", Path = "/files/pBWV7R2w3omzP+Kv5PxT627LiqV3evixcVyN4B9NovI=.png", },
                  new FileModel { Id = 11, Name = "9FXre4iyTJ6PR2kItwfneUxvLFxi8bN402K2VcsZ4dE=.png", Path = "/files/9FXre4iyTJ6PR2kItwfneUxvLFxi8bN402K2VcsZ4dE=.png", },
                  new FileModel { Id = 12, Name = "1rpHDSXaRvlmmbFewuByZ5l02dD0lY99Nfm5TYu9Vdo=.png", Path = "/files/1rpHDSXaRvlmmbFewuByZ5l02dD0lY99Nfm5TYu9Vdo=.png", },
                  new FileModel { Id = 13, Name = "+IAx1JqqRxZudz0ReeJAGz76F5LKfzo5paBh7HCSBc=.png", Path = "/files/+IAx1JqqRxZudz0ReeJAGz76F5LKfzo5paBh7HCSBc=.png", },
                  new FileModel { Id = 14, Name = "FnsrvbI5NPfBBa+wcpa85l1orRZIdwppeOkm1EA5RiA=.png", Path = "/files/FnsrvbI5NPfBBa+wcpa85l1orRZIdwppeOkm1EA5RiA=.png", },
                  new FileModel { Id = 15, Name = "MwDbR+apJTYsCV9tUP4WPs8W0EqEiqG5m5wrca5SZsw=.png", Path = "/files/MwDbR+apJTYsCV9tUP4WPs8W0EqEiqG5m5wrca5SZsw=.png", },
                  new FileModel { Id = 16, Name = "1cDGXpJthPlZ+7Jk7++tTOYNDO0NdvQp6vtYFcpEeE=.png", Path = "/files/1cDGXpJthPlZ+7Jk7++tTOYNDO0NdvQp6vtYFcpEeE=.png", },
                  new FileModel { Id = 17, Name = "8jPLR62nAIKQNMYx1TmBvtK57mq6PB6RnTVrtAm5SZg=.webp", Path = "/files/booking-categories/8jPLR62nAIKQNMYx1TmBvtK57mq6PB6RnTVrtAm5SZg=.webp", },
                  new FileModel { Id = 18, Name = "PWKTeFbPU3hKtS0NS88R+ZkYbZpEHZcRTUxo21bdWQ=.jpg", Path = "/files/booking-categories/PWKTeFbPU3hKtS0NS88R+ZkYbZpEHZcRTUxo21bdWQ=.jpg", },
                  new FileModel { Id = 19, Name = "WvBwu6I7aVKY4M1+UrxtVQ4FBqZoWjiuvwRg393+wc0=.jpg", Path = "/files/booking-categories/WvBwu6I7aVKY4M1+UrxtVQ4FBqZoWjiuvwRg393+wc0=.jpg", },
                  new FileModel { Id = 20, Name = "DpIc5BjZEwT+N6kuEHdQ67EE7gWBrjZBnTlywfWAlo=.jpg", Path = "/files/booking-categories/DpIc5BjZEwT+N6kuEHdQ67EE7gWBrjZBnTlywfWAlo=.jpg", },
                  new FileModel { Id = 21, Name = "ccbGiIK5RdTaNH3FKaLHCFXp9vvNDxNGGefGtA6s0a0=.jpg", Path = "/files/booking-categories/ccbGiIK5RdTaNH3FKaLHCFXp9vvNDxNGGefGtA6s0a0=.jpg", },
                  new FileModel { Id = 22, Name = "SVGx5iqYWcxNoJZGFNAFc9+ZtYXSTWWGdUQdg3DQD2g=.jpg", Path = "/files/booking-categories/SVGx5iqYWcxNoJZGFNAFc9+ZtYXSTWWGdUQdg3DQD2g=.jpg", },
                  new FileModel { Id = 23, Name = "h3DP1vCkB2kLPb2jyy6YpkMi3mJM6IYW1Y07gXNndLI=.jpg", Path = "/files/booking-categories/h3DP1vCkB2kLPb2jyy6YpkMi3mJM6IYW1Y07gXNndLI=.jpg", },
                  new FileModel { Id = 24, Name = "WFBGRejuSFOJ9hY0jm5BSEIX7Zd6vPfGkoQsP3C8A=.jpg", Path = "/files/booking-categories/WFBGRejuSFOJ9hY0jm5BSEIX7Zd6vPfGkoQsP3C8A=.jpg", },
                  new FileModel { Id = 25, Name = "AWKGQV1ZympDIFSlVlvgX8m2XN8bU8hqPoHuqp6aSsk=.jpg", Path = "/files/booking-categories/AWKGQV1ZympDIFSlVlvgX8m2XN8bU8hqPoHuqp6aSsk=.jpg", },
                  new FileModel { Id = 26, Name = "nL4slBus5cwN7eAjhpHr6LHedLqV0WpgwZ64Xt7NsbE=.jpg", Path = "/files/booking-categories/nL4slBus5cwN7eAjhpHr6LHedLqV0WpgwZ64Xt7NsbE=.jpg", },
                  new FileModel { Id = 27, Name = "jFNYJ0G0n69IMehflOLhqJN6L7mvtyvEhWYosFbCD0o=.jpg", Path = "/files/booking-categories/jFNYJ0G0n69IMehflOLhqJN6L7mvtyvEhWYosFbCD0o=.jpg", },
                  new FileModel { Id = 28, Name = "PIKzYCNQ6eJX21q3tEUYIOspOHy7TBAhZjc4yCgXb0=.jpg", Path = "/files/booking-categories/PIKzYCNQ6eJX21q3tEUYIOspOHy7TBAhZjc4yCgXb0=.jpg", },
                  new FileModel { Id = 29, Name = "wSjvY0V4thEVQdc2yc2HuHn3geZZuoJUUiKDp94TmI=.jpg", Path = "/files/booking-categories/wSjvY0V4thEVQdc2yc2HuHn3geZZuoJUUiKDp94TmI=.jpg", },
                  new FileModel { Id = 30, Name = "aCULIjuxi3WuMDOpb4N2nzB2OlXNhu7qtPetG34cWNw=.jpg", Path = "/files/booking-categories/aCULIjuxi3WuMDOpb4N2nzB2OlXNhu7qtPetG34cWNw=.jpg", },
                  new FileModel { Id = 31, Name = "cameLbbE7MwXMEWSpWQb5xelqkRtnd89WSHdQa748=.jpg", Path = "/files/booking-categories/cameLbbE7MwXMEWSpWQb5xelqkRtnd89WSHdQa748=.jpg", },
                  new FileModel { Id = 32, Name = "s+zPgNsDGpzOmiGpErxaD25x38t08YakaWMh4oy+xko=.jpg", Path = "/files/booking-categories/s+zPgNsDGpzOmiGpErxaD25x38t08YakaWMh4oy+xko=.jpg", },
                  new FileModel { Id = 33, Name = "vEsdBlDZSonr9G4nrPC+ADdB05nS3WtD1Vdtg2vEdls=.jpg", Path = "/files/booking-categories/vEsdBlDZSonr9G4nrPC+ADdB05nS3WtD1Vdtg2vEdls=.jpg", },
                  new FileModel { Id = 34, Name = "xlO12jVkOIhTl6V0CAR3uC0clz782hFr60m90ZMoEtc=.jpg", Path = "/files/booking-categories/xlO12jVkOIhTl6V0CAR3uC0clz782hFr60m90ZMoEtc=.jpg", },
                  new FileModel { Id = 35, Name = "YclkZnp1Xn6wxk1eUtjno9cHcS43eefuqhDzSzSUDFU=.jpg", Path = "/files/booking-categories/YclkZnp1Xn6wxk1eUtjno9cHcS43eefuqhDzSzSUDFU=.jpg", },
                  new FileModel { Id = 36, Name = "v1uHZOLG2gjVU1d6EcFeWv61i5U6EJFBWzovIbiTWfc=.jpg", Path = "/files/booking-categories/v1uHZOLG2gjVU1d6EcFeWv61i5U6EJFBWzovIbiTWfc=.jpg", },
                  new FileModel { Id = 37, Name = "28gfiUeA8lD6E5eO4eHc31vvFGarpWk7DoAGwzDd4=.jpg", Path = "/files/booking-categories/28gfiUeA8lD6E5eO4eHc31vvFGarpWk7DoAGwzDd4=.jpg", },
                  new FileModel { Id = 38, Name = "38ULX8oMuuiBBrWmybcDv9mE02zeXuKGyKwxJ0wbbvc=.jpg", Path = "/files/booking-categories/38ULX8oMuuiBBrWmybcDv9mE02zeXuKGyKwxJ0wbbvc=.jpg", },
                  new FileModel { Id = 39, Name = "k60eWzKITm0qHXThVzz+VFtcmDwS+Geqw4qpVaVntww=.jpg", Path = "/files/booking-categories/k60eWzKITm0qHXThVzz+VFtcmDwS+Geqw4qpVaVntww=.jpg", },
                  new FileModel { Id = 40, Name = "UtWw0Kd9VsqxkDAyjdo1kR4pTXgRYtgr8bnIafjm4KA=.jpg", Path = "/files/booking-categories/UtWw0Kd9VsqxkDAyjdo1kR4pTXgRYtgr8bnIafjm4KA=.jpg", },
                  new FileModel { Id = 41, Name = "2cJ9bLYWaRmntd32hJMfHkGSAKl44mL6skW7xBgxSQ=.jpg", Path = "/files/cities/2cJ9bLYWaRmntd32hJMfHkGSAKl44mL6skW7xBgxSQ=.jpg", },
                  new FileModel { Id = 42, Name = "r25bYhQuTGlu2Q3XLxx5AjBOymSwaFoGrE3NkSt3g=.jpg", Path = "/files/cities/r25bYhQuTGlu2Q3XLxx5AjBOymSwaFoGrE3NkSt3g=.jpg", },
                  new FileModel { Id = 43, Name = "AO9WI6rkbYft1QE5Ht7Bea3FacTX8koOpW34qDB1Hxs=.jpg", Path = "/files/cities/AO9WI6rkbYft1QE5Ht7Bea3FacTX8koOpW34qDB1Hxs=.jpg", },
                  new FileModel { Id = 44, Name = "qf+01PybqRDOrxpESro3QvN7bLPIzPHlXtQzXYaRJQ=.jpg", Path = "/files/cities/qf+01PybqRDOrxpESro3QvN7bLPIzPHlXtQzXYaRJQ=.jpg", },
                  new FileModel { Id = 45, Name = "ACCQwXjlZ0HyF0ZEK+9JeiwKmHfbRapg2+hCfoR+GQ=.webp", Path = "/files/cities/ACCQwXjlZ0HyF0ZEK+9JeiwKmHfbRapg2+hCfoR+GQ=.webp", },
                  new FileModel { Id = 46, Name = "zzfyT2YznMbRTX3WMQGcmRvdHWpKFPtZBYakvJyJeFQ=.jpg", Path = "/files/cities/zzfyT2YznMbRTX3WMQGcmRvdHWpKFPtZBYakvJyJeFQ=.jpg", },
                  new FileModel { Id = 47, Name = "wUR7kBl2k5hbmSez3shxGijGAy7he9XsySVgVmThu38=.jpg", Path = "/files/cities/wUR7kBl2k5hbmSez3shxGijGAy7he9XsySVgVmThu38=.jpg", },
                  new FileModel { Id = 48, Name = "iGX8wogugyA1tS2KsT5wiPJtOm72QVPKbKbaTkwC54c=.webp", Path = "/files/cities/iGX8wogugyA1tS2KsT5wiPJtOm72QVPKbKbaTkwC54c=.webp", },
                  new FileModel { Id = 49, Name = "ZMGW71dUcALX3Fmi27UwsbPDRCOdeW7gpVKOPUyRZBs=.jpg", Path = "/files/cities/ZMGW71dUcALX3Fmi27UwsbPDRCOdeW7gpVKOPUyRZBs=.jpg", },
                  new FileModel { Id = 50, Name = "ja9zowNm1GdRAwBxY+kdzv9o6vP9Bi3PqNaBVl2xuQ=.png", Path = "/files/cities/ja9zowNm1GdRAwBxY+kdzv9o6vP9Bi3PqNaBVl2xuQ=.png", },
                  new FileModel { Id = 51, Name = "Qhc5DZhf0xTviHaF2EJ7Y5ppUtPDWfw3xiGHP0y8k8c=.jpg", Path = "/files/cities/Qhc5DZhf0xTviHaF2EJ7Y5ppUtPDWfw3xiGHP0y8k8c=.jpg", },
                  new FileModel { Id = 52, Name = "MnDxHSrTUYmyX8Tsx0qUVRDL33fRQaVaE0+ihCGDoM=.jpg", Path = "/files/cities/MnDxHSrTUYmyX8Tsx0qUVRDL33fRQaVaE0+ihCGDoM=.jpg", },
                  new FileModel { Id = 53, Name = "Yp6XJTcaYN3pDZncxFOSJSsqdXfX0b4yg6zNr9cgg=.jpg", Path = "/files/cities/Yp6XJTcaYN3pDZncxFOSJSsqdXfX0b4yg6zNr9cgg=.jpg", },
                  new FileModel { Id = 54, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 55, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 56, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 57, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 58, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 59, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 60, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 61, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 62, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 63, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 64, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 65, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 66, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 67, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 68, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 69, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 70, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 71, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 72, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 73, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 74, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 75, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 76, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 77, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 78, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 79, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 80, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 81, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 82, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 83, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 84, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 85, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 86, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 87, Name = "", Path = "/files/cities/", },
                  new FileModel { Id = 88, Name = "", Path = "/files/cities/", },
              });
        }
    }
}
